Enable Istio Integration Security Suite With Converter

diff --git a/ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml b/ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
--- a/ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
+++ b/ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
@@ -378,7 +378,7 @@ tests:
           entrypoint \
           prow/integ-suite-ocp.sh \
           pilot 'TestGatewayConformance|TestGateway/managed-owner|TestCNIVersionSkew|TestGateway|TestAuthZCheck|TestKubeInject|TestRevisionTags|TestUninstallByRevision|TestUninstallWithSetFlag|TestUninstallCustomFile|TestUninstallPurge|TestCNIRaceRepair|TestValidation|TestWebhook|TestMultiRevision|TestAnalysisWritesStatus|TestLocality'"
-        # We are skipping failing tests for now, the progress is being tracked in https://issues.redhat.com/browse/OSSM-6316
+        # We are skipping failing tests for now, the progress is being tracked in https://issues.redhat.com/browse/OSSM-9328
       env:
       - name: MAISTRA_NAMESPACE
       - name: MAISTRA_SC_POD
@@ -436,8 +436,67 @@ tests:
           cd /work && \
           entrypoint \
           prow/integ-suite-ocp.sh \
-          telemetry 'TestTraffic/externalname/routed/auto-http|'"
-        # We are skipping failing tests for now, the progress is being tracked in https://issues.redhat.com/browse/OSSM-6316
+          telemetry 'TestDashboard/pilot-dashboard.json|TestProxyTracingOpenTelemetryProvider/grpc_exporter_with_auth|TestGatewayTracing|TestClientTracing|TestServerTracing'"
+        # We are skipping failing tests for now, the progress is being tracked in https://issues.redhat.com/browse/OSSM-10481
+      env:
+      - name: MAISTRA_NAMESPACE
+      - name: MAISTRA_SC_POD
+      - name: XDG_CACHE_HOME
+      from: src
+      grace_period: 30m0s
+      resources:
+        requests:
+          cpu: 100m
+          memory: 100Mi
+      timeout: 3h0m0s
+    workflow: servicemesh-istio-e2e-hypershift
+- as: istio-integration-sail-security
+  steps:
+    cluster_profile: ossm-aws
+    env:
+      BASE_DOMAIN: servicemesh.devcluster.openshift.com
+      MAISTRA_BUILDER_IMAGE: quay-proxy.ci.openshift.org/openshift/ci:ci_maistra-builder_upstream-master
+      MAISTRA_NAMESPACE: maistra-e2e-test
+      MAISTRA_SC_POD: maistra-e2e-test-sc-pod
+      XDG_CACHE_HOME: /tmp/cache
+    test:
+    - as: copy-src
+      cli: latest
+      commands: |
+        # SRC_PATH does end with /. : the content of the source directory is copied into dest directory
+        oc cp ./. "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":/work/
+        oc cp ${KUBECONFIG} ${MAISTRA_NAMESPACE}/${MAISTRA_SC_POD}:/work/ci-kubeconfig
+      env:
+      - name: MAISTRA_NAMESPACE
+      - name: MAISTRA_SC_POD
+      from: src
+      resources:
+        requests:
+          cpu: 100m
+          memory: 100Mi
+      timeout: 10m0s
+    - as: integ-sail-security-test-run
+      cli: latest
+      commands: |
+        cleanup() {
+          echo "Copying artifacts..."
+          oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
+        }
+        trap cleanup EXIT  # Ensure cleanup always runs when the script exits
+        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
+          bash -c "\
+          export KUBECONFIG=/work/ci-kubeconfig && \
+          oc version && \
+          export ARTIFACT_DIR="${ARTIFACT_DIR}" && \
+          export DOCKER_INSECURE_REGISTRIES="default-route-openshift-image-registry.$(oc get routes -A -o jsonpath='{.items[0].spec.host}' | awk -F. '{print substr($0, index($0,$2))}')" && \
+          export BUILD_WITH_CONTAINER="0" && \
+          export CONTROL_PLANE_SOURCE=sail && \
+          export INSTALL_SAIL_OPERATOR=true && \
+          cd /work && \
+          entrypoint \
+          prow/integ-suite-ocp.sh \
+          security 'TestAuthz_CustomServer|TestGatewayAPIRequestAuthentication|TestMultiMtlsGateway|TestMultiTlsGateway|TestNormalization|TestEgressGatewayTls/Mutual_TLS_origination_from_egress_gateway_to_https_endpoint|TestEgressGatewayTls/SIMPLE_TLS_origination_from_egress_gateway_to_https_endpoint|TestPluggedInCACRL|TestTlsGatewaysWithQUIC|TestMtlsGatewaysWithQUIC' 'external_ca|file_mounted_certs|policy_attachment_only'"
+          # We are skipping failing tests for now, the progress is being tracked in https://issues.redhat.com/browse/OSSM-9613
       env:
       - name: MAISTRA_NAMESPACE
       - name: MAISTRA_SC_POD
