Improvement for coopying test artifacts
This improvement will let us collect istio integration test logs even if the tests fail.

diff --git a/ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml b/ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
--- a/ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
+++ b/ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
@@ -135,6 +135,11 @@ tests:
     - as: telemetry-sail-cp-test-run
       cli: latest
       commands: |
+        cleanup() {
+          echo "Copying artifacts..."
+          oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
+        }
+        trap cleanup EXIT  # Ensure cleanup always runs when the script exits
         oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
           bash -c "\
           export KUBECONFIG=/work/ci-kubeconfig && \
@@ -147,12 +152,12 @@ tests:
           entrypoint \
           prow/integ-suite-ocp.sh \
           telemetry"
-        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
       env:
       - name: MAISTRA_NAMESPACE
       - name: MAISTRA_SC_POD
       - name: XDG_CACHE_HOME
       from: src
+      grace_period: 30m0s
       resources:
         requests:
           cpu: 100m
@@ -191,6 +196,11 @@ tests:
     - as: pilot-sail-cp-test-run
       cli: latest
       commands: |
+        cleanup() {
+          echo "Copying artifacts..."
+          oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
+        }
+        trap cleanup EXIT  # Ensure cleanup always runs when the script exits
         oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
           bash -c "\
           export KUBECONFIG=/work/ci-kubeconfig && \
@@ -203,12 +213,12 @@ tests:
           entrypoint \
           prow/integ-suite-ocp.sh \
           pilot 'TestGatewayConformance|TestGateway/managed-owner|TestCNIVersionSkew|TestGateway|TestAuthZCheck|TestKubeInject|TestRevisionTags|TestUninstallByRevision|TestUninstallWithSetFlag|TestUninstallCustomFile|TestUninstallPurge'"
-        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
       env:
       - name: MAISTRA_NAMESPACE
       - name: MAISTRA_SC_POD
       - name: XDG_CACHE_HOME
       from: src
+      grace_period: 30m0s
       resources:
         requests:
           cpu: 100m
