add forced failure
Signed-off-by: Alejandro Brugarolas <abrugaro@redhat.com>

diff --git a/ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-main__4.22.yaml b/ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-main__4.22.yaml
--- a/ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-main__4.22.yaml
+++ b/ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-main__4.22.yaml
@@ -86,8 +86,8 @@ tests:
     - as: test-command
       cli: latest
       commands: |
-        export SKIP_LOG_VERIFICATION="true" INSTALL_NAMESPACE="$OPERATOR_NAMESPACE"
-        make e2e-test
+        echo "Forcing failure to test medik8s-analyze-e2e-failure post-step"
+        exit 1
       env:
       - name: OPERATOR_NAMESPACE
       from: src
