[ossm] Bump OCP version to 4.20 and 4.21 in Sail jobs (#70641)

diff --git a/ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.2__ocp-4.21.yaml b/ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.2__ocp-4.21.yaml
--- a/ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.2__ocp-4.21.yaml
+++ b/ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.2__ocp-4.21.yaml
@@ -1,13 +1,13 @@
 base_images:
   cli:
-    name: "4.19"
+    name: "4.21"
     namespace: ocp
     tag: cli
 build_root:
   image_stream_tag:
     name: maistra-builder
     namespace: ci
-    tag: upstream-master
+    tag: upstream-1.27
   use_build_cache: true
 releases:
   latest:
@@ -15,7 +15,7 @@ releases:
       architecture: amd64
       product: ocp
       stream: nightly
-      version: "4.19"
+      version: "4.21"
 resources:
   '*':
     limits:
@@ -25,11 +25,10 @@ resources:
       memory: 2Gi
 tests:
 - as: e2e-ocp
-  skip_if_only_changed: ^(docs/.*\.md$)|(^[^/]*\.md$)|(^\.github/.*$)
   steps:
     cluster_profile: ossm-aws
     env:
-      MAISTRA_BUILDER_IMAGE: gcr.io/istio-testing/build-tools:master-4d8a6668b6d46b3becc35f9b24467f841bbb020a
+      MAISTRA_BUILDER_IMAGE: gcr.io/istio-testing/build-tools:release-1.27-0ef669e3326567c47323402f8af247931fce234f
       MAISTRA_NAMESPACE: maistra-e2e-test
       MAISTRA_SC_POD: maistra-e2e-test-sc-pod
       XDG_CACHE_HOME: /tmp/cache
@@ -52,23 +51,25 @@ tests:
     - as: e2e-ocp
       cli: latest
       commands: |
-        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" \
-          sh -c "\
-          export KUBECONFIG=/work/ci-kubeconfig && \
-          oc version && \
-          export DOCKER_INSECURE_REGISTRIES="default-route-openshift-image-registry.$(oc get routes -A -o jsonpath='{.items[0].spec.host}' | awk -F. '{print substr($0, index($0,$2))}')" && \
-          export BUILD_WITH_CONTAINER="0" && \
-          export VERSIONS_YAML_FILE=versions.yaml && \
-          cd /work && \
-          entrypoint \
-          # generate everything using versions.yaml not ossm/versions.yaml
-          make gen test.e2e.ocp"
-        oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
+        cleanup() {
+          echo "Copying artifacts..."
+          oc cp "${MAISTRA_NAMESPACE}"/"${MAISTRA_SC_POD}":"${ARTIFACT_DIR}"/. "${ARTIFACT_DIR}"
+        }
+        trap cleanup EXIT  # Ensure cleanup always runs when the script exits
+        oc rsh -n "${MAISTRA_NAMESPACE}" "${MAISTRA_SC_POD}" <<EOF
+          export KUBECONFIG=/work/ci-kubeconfig
+          oc version
+          export DOCKER_INSECURE_REGISTRIES="default-route-openshift-image-registry.$(oc get routes -A -o jsonpath='{.items[0].spec.host}' | awk -F. '{print substr($0, index($0,$2))}')"
+          export BUILD_WITH_CONTAINER="0"
+          cd /work
+          entrypoint make test.e2e.ocp
+        EOF
       env:
       - name: MAISTRA_NAMESPACE
       - name: MAISTRA_SC_POD
       - name: XDG_CACHE_HOME
       from: src
+      grace_period: 30m0s
       resources:
         requests:
           cpu: 200m
@@ -76,7 +77,7 @@ tests:
       timeout: 2h0m0s
     workflow: servicemesh-istio-e2e-profile
 zz_generated_metadata:
-  branch: main
+  branch: release-3.2
   org: openshift-service-mesh
   repo: sail-operator
-  variant: ocp-4.19
+  variant: ocp-4.21
