address feedback
Signed-off-by: Andy Sadler <ansadler@redhat.com>

diff --git a/ci-operator/config/konflux-workspaces/workspaces/konflux-workspaces-workspaces-main.yaml b/ci-operator/config/konflux-workspaces/workspaces/konflux-workspaces-workspaces-main.yaml
--- a/ci-operator/config/konflux-workspaces/workspaces/konflux-workspaces-workspaces-main.yaml
+++ b/ci-operator/config/konflux-workspaces/workspaces/konflux-workspaces-workspaces-main.yaml
@@ -27,56 +27,62 @@ tests:
     product: ocp
     timeout: 1h0m0s
     version: "4.14"
-  run_if_changed: ^.github/workflows/push.yaml$|^server|^operator|^ci
+  run_if_changed: ^.github/workflows/push.yaml$|^server|^operator|^ci|^e2e
   steps:
     test:
     - as: e2e
       cli: latest
       commands: |
+        # TODO(sadlerap): take this out once we unify tooling
         make -C server kustomize
+
+        # set up environment variables
         export KUSTOMIZE="$(realpath server/bin/kustomize)"
         export TAG="pr-${PULL_NUMBER}-${PULL_PULL_SHA:0:8}"
-        export OPERATOR_IMG="quay.io/konflux-workspaces/workspaces-operator:${TAG}"
-        export SERVER_IMG="quay.io/konflux-workspaces/workspaces-server:${TAG}"
+        export QUAY_REPO="quay.io/konflux-workspaces"
+        export OPERATOR_IMG="${QUAY_REPO}/workspaces-operator:${TAG}"
+        export SERVER_IMG="${QUAY_REPO}/workspaces-server:${TAG}"
         export NAMESPACE=workspaces-system
         export USE_INSECURE_TLS=true
-        unset REPO_NAME
+        export SERVER_LOG_LEVEL=-4
+        export E2E_POLL_TIMEOUT=5m
         echo "${TAG}"
 
+        # needed because the build system for kubesaw deploys the latest
+        # version whenever we make a change to openshift/release, which
+        # makes testing very difficult
+        unset REPO_NAME
+
+        # wait for kubesaw images to become available
         while [[ -z "$(skopeo list-tags docker://quay.io/konflux-workspaces/host-operator | grep ${TAG})" ]]; do
             sleep 5
         done
+
+        # deploy kubesaw
         ci/toolchain_manager.sh deploy "${TAG}"
 
+        # wait for workspace images to become available
         while [[ -z "$(skopeo list-tags docker://quay.io/konflux-workspaces/workspaces-operator | grep ${TAG})" ]]; do
             sleep 5
         done
 
-        export SERVER_LOG_LEVEL=-4
-        export E2E_POLL_TIMEOUT=5m
+        # deploy workspaces
         make -C e2e deploy-operator deploy-server
 
-        kubectl get -n "${NAMESPACE}" routes workspaces-rest-api-server -o yaml
-        echo "+++"
-        kubectl get -n "${NAMESPACE}" services workspaces-rest-api-server -o yaml
-
+        # run tests
         if make -C e2e test; then
             exit 0
-        else
-            echo "operator logs:"
-            echo "+++"
-            kubectl logs -n "${NAMESPACE}" deployments/workspaces-controller-manager manager
-            echo "+++"
-            echo "server logs:"
-            echo "+++"
-            kubectl logs -n "${NAMESPACE}" deployments/workspaces-rest-api-server rest-api
-            echo "+++"
-            echo "proxy logs:"
-            echo "+++"
-            kubectl logs -n "${NAMESPACE}" deployments/workspaces-rest-api-server proxy
-            echo "+++"
-            exit 1
         fi
+
+        # tests failed, dump logs
+        printf "operator logs:\n+++\n"
+        kubectl logs -n "${NAMESPACE}" deployments/workspaces-controller-manager manager
+        printf "+++\nserver logs:\n+++\n"
+        kubectl logs -n "${NAMESPACE}" deployments/workspaces-rest-api-server rest-api
+        printf "+++\nproxy logs:\n+++\n"
+        kubectl logs -n "${NAMESPACE}" deployments/workspaces-rest-api-server proxy
+        echo "+++\n"
+        exit 1
       from: src
       resources:
         requests:
