jobs/4.12: s/machine-os-content/rhel-coreos-8/
xref  https://github.com/openshift/os/issues/1017

This is part of ensuring we only have one `rhel-coreos-8` image
that is copied from ART into CI.

diff --git a/ci-operator/jobs/openshift/release/openshift-release-release-4.12-periodics.yaml b/ci-operator/jobs/openshift/release/openshift-release-release-4.12-periodics.yaml
--- a/ci-operator/jobs/openshift/release/openshift-release-release-4.12-periodics.yaml
+++ b/ci-operator/jobs/openshift/release/openshift-release-release-4.12-periodics.yaml
@@ -44,37 +44,42 @@ periodics:
 
         # if the source and destination are identical, do nothing
         export KUBECONFIG=/etc/app.ci/kubeconfig
-        from=$( oc get istag -n "${TAG_NS}" "${TAG_SOURCE}" -o template='{{ .image.metadata.name }}' )
+        from=$( oc get istag -n "${TAG_NS}" "${TAG}:${BRANCH}" -o template='{{ .image.metadata.name }}' )
         to=$( oc get istag --ignore-not-found -n ocp "${BRANCH}:${TAG}" -o template='{{ .image.metadata.name }}' )
+        from_extensions=$( oc get istag -n "${TAG_NS}" "${TAG}-extensions:${BRANCH}" -o template='{{ .image.metadata.name }}' )
+        to_extensions=$( oc get istag --ignore-not-found -n ocp "${BRANCH}:${TAG}-extensions" -o template='{{ .image.metadata.name }}' )
         unset KUBECONFIG
         if [[ "${from}" == "${to}" ]]; then
-          echo "info: ${TAG_NS}/${TAG_SOURCE} matches ocp/${BRANCH}:${TAG}"
+          echo "info: ${TAG_NS}/${TAG}:${BRANCH} matches ocp/${BRANCH}:${TAG}"
           exit 0
         fi
-        echo "Will promote ${from}, current is ${to}"
+        echo "Will promote ${TAG} ${from}, current is ${to}"
+        echo "Will promote ${TAG}-extensions ${from_extensions}, current is ${to_extensions}"
 
         # error out if the image isn't on quay
         to_quay="quay.io/openshift-release-dev/ocp-v4.0-art-dev@${from}"
-        if ! oc image info -a "/usr/local/pull-secret/.dockerconfigjson" "${to_quay}"; then
-          echo "error: The source image has not been pushed to quay ${from}"
-          exit 1
-        fi
+        to_quay_extensions="quay.io/openshift-release-dev/ocp-v4.0-art-dev@${from_extensions}"
+        for img in ${to_quay} ${to_quay_extensions}; do
+          if ! oc image info -a "/usr/local/pull-secret/.dockerconfigjson" "${img}"; then
+            echo "error: The source image has not been pushed to quay ${img}"
+            exit 1
+          fi
+        done
 
         # verify the tests pass
         ci-operator $@
 
         # also tag the image into the ocp private stream
         oc tag "${to_quay}" "ocp-private/${BRANCH}-priv:${TAG}"
+        oc tag "${to_quay_extensions}" "ocp-private/${BRANCH}-priv:${TAG}-extensions"
       - ""
       env:
       - name: TAG_NS
         value: rhcos
       - name: TAG
-        value: machine-os-content
+        value: rhel-coreos-8
       - name: BRANCH
         value: "4.12"
-      - name: TAG_SOURCE
-        value: machine-os-content:$(BRANCH)
       - name: UNRESOLVED_CONFIG
         value: |
           tag_specification:
@@ -85,6 +90,7 @@ periodics:
             namespace: ocp
             additional_images:
               $(TAG): $(TAG)
+              $(TAG)-extensions: $(TAG)-extensions
           build_root:
             image_stream_tag:
               name: release
@@ -95,12 +101,21 @@ periodics:
               name: $(TAG)
               namespace: rhcos
               tag: "4.12"
+            $(TAG)-extensions:
+              name: $(TAG)-extensions
+              namespace: rhcos
+              tag: "4.12"
           raw_steps:
           - output_image_tag_step:
               from: $(TAG)
               to:
                 name: stable
                 tag: $(TAG)
+          - output_image_tag_step:
+              from: $(TAG)-extensions
+              to:
+                name: stable
+                tag: $(TAG)-extensions
           resources:
             '*':
               limits:
@@ -211,13 +226,13 @@ periodics:
       - name: TAG_NS
         value: rhcos
       - name: TAG
-        value: machine-os-content
+        value: rhel-coreos-8
       - name: BRANCH
         value: "4.12"
       - name: ARCH
         value: s390x
       - name: TAG_SOURCE
-        value: machine-os-content:$(BRANCH)-$(ARCH)
+        value: rhel-coreos-8:$(BRANCH)-$(ARCH)
       image: ci-operator:latest
       imagePullPolicy: Always
       name: ""
@@ -276,13 +291,13 @@ periodics:
       - name: TAG_NS
         value: rhcos
       - name: TAG
-        value: machine-os-content
+        value: rhel-coreos-8
       - name: BRANCH
         value: "4.12"
       - name: ARCH
         value: ppc64le
       - name: TAG_SOURCE
-        value: machine-os-content:$(BRANCH)-$(ARCH)
+        value: rhel-coreos-8:$(BRANCH)-$(ARCH)
       image: ci-operator:latest
       imagePullPolicy: Always
       name: ""
