Port 4.3-to-4.4-to-4.5-to-4.6-to-4.7-ci to workflows

diff --git a/ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml b/ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
--- a/ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
+++ b/ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
@@ -4690,7 +4690,7 @@ periodics:
     job-test: e2e
     pj-rehearse.openshift.io/can-be-rehearsed: "true"
     release.openshift.io/verify: "true"
-  name: release-openshift-origin-installer-e2e-aws-upgrade-4.3-to-4.4-to-4.6-to-4.7-ci
+  name: release-openshift-origin-installer-e2e-aws-upgrade-4.3-to-4.4-to-4.5-to-4.6-to-4.7-ci
   spec:
     containers:
     - args:
@@ -4713,31 +4713,34 @@ periodics:
         data=$(ARTIFACTS)/release.json
 
         if ! curl --fail -X GET -G --location https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4-stable/latest --data-urlencode 'in=>4.3.0 <4.4.0-0' > ${data}; then
-          echo "error: Could not find an initial version"
+          echo "error: Could not find 4.3 version"
           exit 1
         fi
-        export RELEASE_IMAGE_INITIAL=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec")' "${data}" )
+        export RELEASE_IMAGE_INITIAL=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec"])' "${data}" )
 
-        if ! curl --fail -X GET -G --location https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4-stable/latest --data-urlencode 'in=>4.4.0 <4.6.0-0' > ${data}; then
-          echo "error: Could not find a middle version"
+        if ! curl --fail -X GET -G --location https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4-stable/latest --data-urlencode 'in=>4.4.0 <4.5.0-0' > ${data}; then
+          echo "error: Could not find 4.4 version"
           exit 1
         fi
-        next_0=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec")' "${data}" )
+        export RELEASE_4_4=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec"])' "${data}" )
+
+        if ! curl --fail -X GET -G --location https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4-stable/latest --data-urlencode 'in=>4.5.0 <4.6.0-0' > ${data}; then
+          echo "error: Could not find 4.5 version"
+          exit 1
+        fi
+        export RELEASE_4_5=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec"])' "${data}" )
 
         if ! curl --fail -X GET -G --location https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.6.0-0.nightly/latest > ${data}; then
           echo "error: Could not find newest version"
           exit 1
         fi
-        next_1=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec")' "${data}" )
+        export RELEASE_4_6=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec"])' "${data}" )
 
         if ! curl --fail -X GET -G --location https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.7.0-0.ci/latest > ${data}; then
           echo "error: Could not find newest version"
           exit 1
         fi
-        next_2=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec")' "${data}" )
-
-        export RELEASE_IMAGE_LATEST=${next_2}
-        export CONFIG_SPEC="${CONFIG_SPEC/RELEASE_IMAGES/$next_0,$next_1,$next_2}"
+        export RELEASE_4_7=$( python -c 'from __future__ import print_function; import json,sys; print(json.load(open(sys.argv[1], "r"))["pullSpec"])' "${data}" )
 
         ci-operator $@
       - ""
@@ -4746,7 +4749,7 @@ periodics:
         value: "4.3"
       - name: CLUSTER_TYPE
         value: aws
-      - name: CONFIG_SPEC
+      - name: UNRESOLVED_CONFIG
         value: |
           tag_specification:
             name: "$(BRANCH)"
@@ -4759,25 +4762,27 @@ periodics:
                 cpu: 100m
                 memory: 200Mi
           tests:
-          - as: e2e-$(CLUSTER_TYPE)
-            commands: TEST_SUITE=openshift/conformance/parallel run-tests
-            openshift_installer:
-              cluster_profile: "$(CLUSTER_TYPE)"
-          - as: e2e-$(CLUSTER_TYPE)-serial
-            commands: TEST_SUITE=openshift/conformance/serial run-tests
-            openshift_installer:
-              cluster_profile: "$(CLUSTER_TYPE)"
           - as: e2e-$(CLUSTER_TYPE)-upgrade
-            commands: |
-              TEST_SUITE=all IMAGE=RELEASE_IMAGES run-upgrade-tests
-              TEST_SUITE=openshift/conformance/parallel run-tests
-            openshift_installer:
+            steps:
               cluster_profile: "$(CLUSTER_TYPE)"
-              upgrade: true
-          - as: launch-$(CLUSTER_TYPE)
-            commands: sleep 9000 & wait
-            openshift_installer:
-              cluster_profile: "$(CLUSTER_TYPE)"
+              workflow: openshift-upgrade-$(CLUSTER_TYPE)-loki
+              test:
+              - ref: openshift-e2e-test
+                dependencies:
+                - env: OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE
+                  name: "$(RELEASE_4_4)"
+              - ref: openshift-e2e-test
+                dependencies:
+                - env: OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE
+                  name: "$(RELEASE_4_5)"
+              - ref: openshift-e2e-test
+                dependencies:
+                - env: OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE
+                  name: "$(RELEASE_4_6)"
+              - ref: openshift-e2e-test
+                dependencies:
+                - env: OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE
+                  name: "$(RELEASE_4_7)"
       image: ci-operator:latest
       imagePullPolicy: Always
       name: ""
