ushift: restore periodics config

diff --git a/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml b/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
--- a/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
+++ b/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
@@ -11,6 +11,10 @@ base_images:
     name: "4.13"
     namespace: ocp
     tag: tests
+  ubi-minimal:
+    name: ubi-minimal
+    namespace: ocp
+    tag: "8"
 build_root:
   image_stream_tag:
     name: release
@@ -41,8 +45,6 @@ images:
     RUN dnf install -y jq && dnf clean all && rm -rf /var/cache/dnf/*
     ENV PAYLOAD_PATH=$HOME/payload
     WORKDIR $PAYLOAD_PATH
-    COPY --from=builder /go/src/github.com/openshift/microshift/scripts/devenv-builder/configure-vm.sh usr/bin/configure-vm.sh
-    RUN chmod 755 usr/bin/configure-vm.sh
     COPY oc openshift-tests usr/bin/
     RUN chmod 755 usr/bin/oc && ln -rs usr/bin/oc usr/bin/kubectl
     COPY --from=builder /go/src/github.com/openshift/microshift/_output/rpmbuild/RPMS/*/*.rpm packages/
@@ -63,73 +65,90 @@ images:
       - destination_dir: .
         source_path: /usr/bin/openshift-tests
   to: dependency-payload
-promotion:
-  excluded_images:
-  - dependency-payload
-  - microshift-validate
-  name: "4.13"
-  namespace: ocp
+- dockerfile_literal: |
+    # build
+    FROM ubi-minimal
+    ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
+    ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
+    RUN echo -n "${YQ_HASH} -" > /tmp/sum.txt ; \
+        if ! (curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null); then \
+          echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
+          exit 1 ; \
+        fi ; \
+        chmod +x /tmp/yq && mv /tmp/yq /usr/bin/yq
+  from: ubi-minimal
+  to: yq-cli
+- dockerfile_literal: |
+    FROM src
+    COPY yq /usr/bin/yq
+    RUN yum install -y --nodocs python3-devel && \
+        pip3 install pygithub GitPython && \
+        dnf clean all && \
+        rm -rf /var/cache/dnf/*
+  from: src
+  inputs:
+    yq-cli:
+      paths:
+      - destination_dir: .
+        source_path: /usr/bin/yq
+  to: microshift-rebase
+releases:
+  arm64-latest:
+    candidate:
+      architecture: arm64
+      product: ocp
+      stream: nightly
+      version: "4.13"
+  latest:
+    candidate:
+      product: ocp
+      stream: nightly
+      version: "4.13"
 resources:
   '*':
     limits:
       memory: 4Gi
     requests:
       cpu: 100m
-      memory: 200Mi
-tag_specification:
-  name: "4.13"
-  namespace: ocp
+      memory: 800Mi
 tests:
-- as: verify
-  cluster: build02
-  commands: make verify
-  container:
-    from: src
+- as: copr-rpm-health-check
+  cron: 0 0 * * *
+  steps:
+    cluster_profile: gcp
+    env:
+      GOOGLE_COMPUTE_IMAGE_NAME: rhel-9-v20230203
+    workflow: openshift-microshift-e2e-copr-install
 - as: test-unit
-  cluster: build02
   commands: make test-unit
   container:
     from: src
+  cron: 0 0 * * *
 - as: test-srpm
-  cluster: build02
   commands: make srpm
   container:
     from: src
-  run_if_changed: ^(rpm/*|packaging/.*|Makefile)
-- as: e2e-rpm-install
-  cluster: build02
-  run_if_changed: ^(assets/.*|cmd/.*|pkg/.*|packaging/.*|vendor/.*|go\.sum|go\.mod|Makefile|.*\.sh)
+  cron: 0 0 * * *
+- as: e2e-openshift-conformance-sig-api-machinery
+  cron: 0 0 * * *
   steps:
     cluster_profile: gcp
     env:
       GOOGLE_COMPUTE_IMAGE_NAME: rhel-9-v20230203
-    workflow: openshift-microshift-e2e-rpm-install
-- as: e2e-openshift-conformance-reduced
-  cluster: build02
-  run_if_changed: ^(assets/.*|cmd/.*|pkg/.*|packaging/.*|vendor/.*|go\.sum|go\.mod|Makefile|.*\.sh)
-  steps:
-    cluster_profile: gcp
-    env:
-      GOOGLE_COMPUTE_IMAGE_NAME: rhel-9-v20230203
-    workflow: openshift-microshift-e2e-openshift-conformance-reduced
+    workflow: openshift-microshift-e2e-openshift-conformance-sig-api-machinery
 - as: e2e-reboot
-  cluster: build02
-  run_if_changed: ^(assets/.*|cmd/.*|pkg/.*|packaging/.*|vendor/.*|go\.sum|go\.mod|Makefile)
+  cron: 0 0 * * *
   steps:
     cluster_profile: gcp
     env:
       GOOGLE_COMPUTE_IMAGE_NAME: rhel-9-v20230203
     workflow: openshift-microshift-e2e-reboot-tests
-- as: e2e-router-smoke-test
-  cluster: build02
-  optional: true
-  run_if_changed: ^(assets/.*|cmd/.*|pkg/.*|packaging/.*|vendor/.*|go\.sum|go\.mod|Makefile|.*\.sh)
+- as: rebase-on-nightlies
+  cron: 0 5 * * 1-5
   steps:
-    cluster_profile: gcp
-    env:
-      GOOGLE_COMPUTE_IMAGE_NAME: rhel-9-v20230203
-    workflow: openshift-microshift-e2e-router-smoke-test
+    workflow: openshift-microshift-rebase
 zz_generated_metadata:
   branch: main
   org: openshift
   repo: microshift
+  variant: periodics
