WIP

diff --git a/ci-operator/config/openshift/microshift/openshift-microshift-main.yaml b/ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
--- a/ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
+++ b/ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
@@ -17,23 +17,23 @@ build_root:
     namespace: openshift
     tag: rhel-8-release-golang-1.19-openshift-4.13
 images:
-- dockerfile_literal: |
-    FROM src
-    RUN pip3 install --upgrade pip && \
-      pip3 install setuptools-rust cryptography pyyaml pygithub gitpython
-    ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
-    ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
-    RUN echo -n "${YQ_HASH} -" > /tmp/sum.txt ; \
-          if ! (curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null); then \
-            echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
-            exit 1 ; \
-          fi ; \
-          chmod +x /tmp/yq && mv /tmp/yq /usr/bin/yq
-  inputs:
-    src:
-      as:
-      - src
-  to: rebase-payload
+# - dockerfile_literal: |
+#     FROM src
+#     RUN pip3 install --upgrade pip && \
+#       pip3 install setuptools-rust cryptography pyyaml pygithub gitpython
+#     ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
+#     ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
+#     RUN echo -n "${YQ_HASH} -" > /tmp/sum.txt ; \
+#           if ! (curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null); then \
+#             echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
+#             exit 1 ; \
+#           fi ; \
+#           chmod +x /tmp/yq && mv /tmp/yq /usr/bin/yq
+#   inputs:
+#     src:
+#       as:
+#       - src
+#   to: rebase-payload
 - dockerfile_literal: |
     FROM src as rpms
     RUN dnf install --setopt=tsflags=nodocs -y selinux-policy-devel
@@ -47,6 +47,8 @@ images:
 
     COPY microshift /microshift
     COPY --from=rpms /rpms.tar /rpms.tar
+    RUN pip3 install --upgrade pip && \
+       pip3 install setuptools-rust
   inputs:
     cli:
       paths:
@@ -66,10 +68,45 @@ images:
       as:
       - test-runtime
   to: microshift-test-payload
+# - dockerfile_literal: |
+#     FROM src as rpms
+#     RUN dnf install --setopt=tsflags=nodocs -y selinux-policy-devel
+#     RUN make rpm && TARGET_ARCH=aarch64 make rpm
+#     RUN tar cvf /rpms.tar -C _output/rpmbuild/RPMS/ .
+
+#     FROM redhat/ubi9
+#     RUN printf '%s\n' \
+#     '[google-cloud-sdk]' \
+#     'name=Google Cloud SDK' \
+#     'baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64' \
+#     'enabled=1' \
+#     'gpgcheck=0' \
+#     'repo_gpgcheck=0' \
+#     'gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg' \
+#     '      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg' > /etc/yum.repos.d/google-cloud-sdk.repo
+
+#     COPY oc /usr/bin/
+
+#     COPY microshift /microshift
+#     COPY --from=rpms /rpms.tar /rpms.tar
+#     RUN dnf install --setopt=tsflags=nodocs -y python3 python3-pip google-cloud-sdk-365.0.1 git make
+#   inputs:
+#     cli:
+#       paths:
+#       - destination_dir: .
+#         source_path: /usr/bin/oc
+#     src:
+#       as:
+#       - src
+#       paths:
+#       - destination_dir: .
+#         source_path: /go/src/github.com/openshift/microshift
+#   to: rf-test-payload
 promotion:
   excluded_images:
   - microshift-test-payload
-  - rebase-payload
+  # - rf-test-payload
+  # - rebase-payload
   name: "4.14"
   namespace: ocp
 releases:
