define yq fetch/check and rebaser image

diff --git a/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml b/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
--- a/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
+++ b/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
@@ -19,11 +19,42 @@ base_images:
     name: "4.10"
     namespace: ocp
     tag: tests
+  ubi:
+    name: "ubi"
+    namespace: "ocp"
+    tag: "8"
 build_root:
   image_stream_tag:
     name: release
     namespace: openshift
     tag: rhel-8-release-golang-1.17-openshift-4.10
+images:
+- dockerfile_literal: |
+    FROM base as download
+    ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64 
+    ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
+    RUN echo "${YQ_HASH}" > /tmp/hash.txt
+    RUN curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt >/dev/null 2>/dev/null || \
+        { echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" exit 1 ; }
+    RUN chmod +x /tmp/yq      
+    FROM base
+    COPY --from=download /tmp/yq /usr/bin/yq
+  inputs:
+    ubi:
+      as:
+      - "base"
+  from: src
+  to: yq-cli
+- dockerfile_literal: |
+    FROM src
+    COPY yq /usr/bin/yq
+  from: src
+  to: rebaser
+  inputs:
+    yq-cli:
+      paths:
+      - destination_dir: "."
+        source_path: "/usr/bin/yq"
 releases:
   arm64-latest:
     candidate:
