ushift rebase presubmit

diff --git a/ci-operator/config/openshift/microshift/openshift-microshift-main.yaml b/ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
--- a/ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
+++ b/ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
@@ -11,12 +11,43 @@ base_images:
     name: "4.13"
     namespace: ocp
     tag: tests
+  ubi-minimal:
+    name: ubi-minimal
+    namespace: ocp
+    tag: "8"
 build_root:
   image_stream_tag:
     name: release
     namespace: openshift
     tag: rhel-8-release-golang-1.19-openshift-4.13
 images:
+- dockerfile_literal: |
+    # build
+    FROM ubi-minimal
+    ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
+    ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
+    RUN echo -n "${YQ_HASH} -" > /tmp/sum.txt ; \
+        if ! (curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null); then \
+          echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
+          exit 1 ; \
+        fi ; \
+        chmod +x /tmp/yq && mv /tmp/yq /usr/bin/yq
+  from: ubi-minimal
+  to: yq-cli
+- dockerfile_literal: |
+    FROM src
+    COPY yq /usr/bin/yq
+    RUN yum install -y --nodocs python3-devel && \
+        pip3 install pygithub GitPython && \
+        dnf clean all && \
+        rm -rf /var/cache/dnf/*
+  from: src
+  inputs:
+    yq-cli:
+      paths:
+      - destination_dir: .
+        source_path: /usr/bin/yq
+  to: microshift-rebase
 - dockerfile_literal: |
     FROM libvirt-installer
     COPY validate-microshift /tmp/validate-microshift
@@ -65,6 +96,7 @@ promotion:
   excluded_images:
   - dependency-payload
   - microshift-validate
+  - microshift-rebase
   name: "4.13"
   namespace: ocp
 resources:
@@ -157,6 +189,11 @@ tests:
   steps:
     cluster_profile: gcp
     workflow: openshift-microshift-e2e-router-smoke-test
+- as: rebase-presubmit
+  optional: true
+  run_if_changed: ^(assets/.*|scripts/auto-rebase/.*)
+  steps:
+    workflow: openshift-microshift-rebase-presubmit
 zz_generated_metadata:
   branch: main
   org: openshift
