fix RUN directive

diff --git a/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml b/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
--- a/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
+++ b/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
@@ -35,14 +35,14 @@ images:
     ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
     ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
     RUN echo -n "${YQ_HASH} -" > /tmp/sum.txt && \
-    { \
-      curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null || \
       { \
-        echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
-        exit 1 ; \
+        curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null || \
+        { \
+          echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
+          exit 1 ; \
+        } ; \
+        chmod +x /tmp/yq ; \
       }
-      chmod +x /tmp/yq ; \
-    }
     # output
     FROM ubi8-minimal
     COPY --from=base /tmp/yq /usr/bin/yq
