improve RUN layer cmd grouping

diff --git a/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml b/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
--- a/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
+++ b/ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
@@ -19,7 +19,7 @@ base_images:
     name: "4.10"
     namespace: ocp
     tag: tests
-  ubi-minimal:
+  ubi8-minimal:
     name: ubi-minimal
     namespace: ocp
     tag: "8"
@@ -30,20 +30,27 @@ build_root:
     tag: rhel-8-release-golang-1.17-openshift-4.10
 images:
 - dockerfile_literal: |
-    FROM base as download
+    # build
+    FROM ubi8-minimal as base
     ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
     ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
-    RUN echo "${YQ_HASH}" > /tmp/hash.txt
-    RUN curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null || \
-        { echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" exit 1 ; }
-    RUN chmod +x /tmp/yq
-    FROM base
-    COPY --from=download /tmp/yq /usr/bin/yq
-  from: src
+    RUN echo -n "${YQ_HASH} -" > /tmp/sum.txt && \
+    { \
+      curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null || \
+      { \
+        echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
+        exit 1 ; \
+      }
+      chmod +x /tmp/yq ; \
+    }
+    # output
+    FROM ubi8-minimal
+    COPY --from=base /tmp/yq /usr/bin/yq
+  from: ubi8-minimal
   inputs:
-    ubi-minimal:
+    ubi8-minimal:
       as:
-      - base
+      - ubi8-minimal
   to: yq-cli
 - dockerfile_literal: |
     FROM src
