USHIFT-953 Optimize MicroShift images (#37170)
* Optimize MicroShift CI images

* use root image for sos

diff --git a/ci-operator/config/openshift/microshift/openshift-microshift-release-4.15.yaml b/ci-operator/config/openshift/microshift/openshift-microshift-release-4.15.yaml
--- a/ci-operator/config/openshift/microshift/openshift-microshift-release-4.15.yaml
+++ b/ci-operator/config/openshift/microshift/openshift-microshift-release-4.15.yaml
@@ -3,10 +3,6 @@ base_images:
     name: "4.15"
     namespace: ocp
     tag: cli
-  libvirt-installer:
-    name: "4.15"
-    namespace: ocp
-    tag: libvirt-installer
   test-bin:
     name: "4.15"
     namespace: ocp
@@ -16,92 +12,78 @@ base_images:
     namespace: ocp
     tag: "8"
 build_root:
-  image_stream_tag:
-    name: release
-    namespace: openshift
-    tag: rhel-8-release-golang-1.19-openshift-4.13
+  project_image:
+    dockerfile_literal: |
+      FROM registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.13
+      USER root
+      RUN echo -e '[google-cloud-sdk]\n\
+      name=Google Cloud SDK\n\
+      baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64\n\
+      enabled=1\n\
+      gpgcheck=1\n\
+      repo_gpgcheck=1\n\
+      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg\n\
+             https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg' > /etc/yum.repos.d/google-cloud-sdk.repo
+      RUN dnf update -y && \
+          dnf install --setopt=tsflags=nodocs -y \
+              gcc glibc-static google-cloud-sdk-365.0.1 jq make python3-devel rpm-build selinux-policy-devel util-linux && \
+          pip3 install \
+              pygithub GitPython && \
+          dnf clean all && rm -rf /var/cache/dnf/*
+      ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
+      ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
+      RUN echo -n "${YQ_HASH} -" > /tmp/sum.txt ; \
+          if ! (curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null); then \
+            echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
+            exit 1 ; \
+          fi ; \
+          chmod +x /tmp/yq && mv /tmp/yq /usr/bin/yq
+  use_build_cache: true
 images:
 - dockerfile_literal: |
-    FROM libvirt-installer
-    COPY validate-microshift /tmp/validate-microshift
-  from: libvirt-installer
-  inputs:
-    src:
-      paths:
-      - destination_dir: .
-        source_path: /go/src/github.com/openshift/microshift/validate-microshift
-  to: microshift-validate
-- dockerfile_literal: |
-    FROM registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.13 as builder
-    RUN dnf install --setopt=tsflags=nodocs -y \
-        rpm-build glibc-static gcc selinux-policy-devel util-linux && \
-        dnf clean all && \
-        rm -rf /var/cache/dnf/*
-    RUN ls -lA
-    RUN make rpm
-    RUN TARGET_ARCH=aarch64 make rpm
-    FROM libvirt-installer
+    FROM root
     USER root
     ENV HOME=/tmp/secret
-    RUN dnf install -y jq && dnf clean all && rm -rf /var/cache/dnf/*
     ENV PAYLOAD_PATH=$HOME/payload
     WORKDIR $PAYLOAD_PATH
-    COPY --from=builder /go/src/github.com/openshift/microshift/scripts/devenv-builder/configure-vm.sh usr/bin/configure-vm.sh
-    COPY --from=builder /go/src/github.com/openshift/microshift/docs/config/busybox_running_check.sh usr/bin/busybox_running_check.sh
-    RUN chmod 755 usr/bin/configure-vm.sh usr/bin/busybox_running_check.sh
+
     COPY oc openshift-tests usr/bin/
     RUN chmod 755 usr/bin/oc && ln -rs usr/bin/oc usr/bin/kubectl
-    COPY --from=builder /go/src/github.com/openshift/microshift/_output/rpmbuild/RPMS/*/*.rpm packages/
+
+    COPY validate-microshift /tmp/validate-microshift
+    COPY busybox_running_check.sh configure-vm.sh usr/bin/
+    RUN chmod 755 usr/bin/configure-vm.sh usr/bin/busybox_running_check.sh
+
+    COPY ./RPMS/*/*.rpm packages/
     RUN tar -cvf payload.tar . && chmod -R a+rw "${HOME}"
   inputs:
     cli:
       paths:
       - destination_dir: .
         source_path: /usr/bin/oc
-    libvirt-installer:
+    root:
       as:
-      - libvirt-installer
+      - root
+    rpms:
+      paths:
+      - destination_dir: .
+        source_path: /go/src/github.com/openshift/microshift/_output/rpmbuild/RPMS
     src:
-      as:
-      - registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.13
+      paths:
+      - destination_dir: .
+        source_path: /go/src/github.com/openshift/microshift/scripts/devenv-builder/configure-vm.sh
+      - destination_dir: .
+        source_path: /go/src/github.com/openshift/microshift/validate-microshift
+      - destination_dir: .
+        source_path: /go/src/github.com/openshift/microshift/docs/config/busybox_running_check.sh
     test-bin:
       paths:
       - destination_dir: .
         source_path: /usr/bin/openshift-tests
-  to: dependency-payload
-- dockerfile_literal: |
-    # build
-    FROM ubi-minimal
-    ENV YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64
-    ENV YQ_HASH=9e35b817e7cdc358c1fcd8498f3872db169c3303b61645cc1faf972990f37582
-    RUN echo -n "${YQ_HASH} -" > /tmp/sum.txt ; \
-        if ! (curl -Ls "${YQ_URL}" | tee /tmp/yq | sha256sum -c /tmp/sum.txt &>/dev/null); then \
-          echo "ERROR: Expected file at ${YQ_URL} to have checksum ${YQ_HASH} but instead got $(sha256sum </tmp/yq | cut -d' ' -f1)" ; \
-          exit 1 ; \
-        fi ; \
-        chmod +x /tmp/yq && mv /tmp/yq /usr/bin/yq
-  from: ubi-minimal
-  to: yq-cli
-- dockerfile_literal: |
-    FROM src
-    COPY yq /usr/bin/yq
-    RUN yum install -y --nodocs python3-devel && \
-        pip3 install pygithub GitPython && \
-        dnf clean all && \
-        rm -rf /var/cache/dnf/*
-  from: src
-  inputs:
-    yq-cli:
-      paths:
-      - destination_dir: .
-        source_path: /usr/bin/yq
-  to: microshift-rebase
+  to: microshift-test-payload
 promotion:
   excluded_images:
-  - dependency-payload
-  - microshift-validate
-  - yq-cli
-  - microshift-rebase
+  - microshift-test-payload
   name: "4.15"
   namespace: ocp
 releases:
@@ -123,6 +105,7 @@ resources:
     requests:
       cpu: 100m
       memory: 200Mi
+rpm_build_commands: make rpm; TARGET_ARCH=aarch64 make rpm
 tag_specification:
   name: "4.15"
   namespace: ocp
