Revert "Merge pull request #1527 from stevekuznetsov/skuznets/test-entrypoint"
This reverts commit b194c78bf801a4147f0ae6e625607133cfe7dba2, reversing
changes made to ef677a2648fc61728a82e59cc495a9ab87ece9c6.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

diff --git a/ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml b/ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
--- a/ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
+++ b/ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
@@ -17,6 +17,12 @@ parameters:
 - name: CLUSTER_TYPE
   value: "azure"
   required: true
+- name: TEST_FOCUS
+- name: TEST_SKIP
+  value: "\\[local\\]"
+- name: TEST_FOCUS_SERIAL
+- name: TEST_SKIP_SERIAL
+  value: "\\[local\\]"
 
 objects:
 
@@ -97,7 +103,7 @@ objects:
             sleep 15 & wait
             continue
           fi
-          # if we got admin kubeconfig file with failure marker, ignore. Teardown is in progress.
+          # if we got admin kubeconfig file with failure marker, ignore. Teardown is in progress. 
           if [[ -f  /tmp/shared/exit ]]; then
              exit 1
           fi
@@ -115,23 +121,20 @@ objects:
         #       autodetected from the running cluster.
         # TODO: bump nodes up to 40 again
         source /tmp/shared/overrides
-        function run-tests() {
-          if [[ -n "${TEST_FOCUS}" ]]; then
-            ginkgo -v -noColor -nodes=30 $( which extended.test ) -- \
-              -ginkgo.focus="${TEST_FOCUS}" -ginkgo.skip="${TEST_SKIP:-"\\[local\\]"}" \
-              -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit \
-              -test.timeout=2h ${PROVIDER_ARGS-} || rc=$?
-          fi
-          if [[ -n "${TEST_FOCUS_SERIAL}" ]]; then
-            ginkgo -v -noColor -nodes=1 $( which extended.test ) -- \
-              -ginkgo.focus="${TEST_FOCUS_SERIAL}" -ginkgo.skip="${TEST_SKIP_SERIAL:-"\\[local\\]"}" \
-              -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit/serial \
-              -test.timeout=2h ${PROVIDER_ARGS-} || rc=$?
-          fi
-          exit ${rc:-0}
-        }
-
-        ${TEST_COMMAND}
+        set -x
+        if [[ -n "${TEST_FOCUS}" ]]; then
+          ginkgo -v -noColor -nodes=30 $( which extended.test ) -- \
+            -ginkgo.focus="${TEST_FOCUS}" -ginkgo.skip="${TEST_SKIP}" \
+            -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit \
+            -test.timeout=2h || rc=$?
+        fi
+        if [[ -n "${TEST_FOCUS_SERIAL}" ]]; then
+          ginkgo -v -noColor -nodes=1 $( which extended.test ) -- \
+            -ginkgo.focus="${TEST_FOCUS_SERIAL}" -ginkgo.skip="${TEST_SKIP_SERIAL}" \
+            -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit/serial \
+            -test.timeout=2h || rc=$?
+        fi
+        exit ${rc:-0}
 
     # Runs an install
     - name: setup
@@ -161,8 +164,7 @@ objects:
        #!/bin/bash
         set -euo pipefail
 
-        # trap acts as a switch/router for the next phases
-        trap 'rc=$?; if [[ $rc -ne 0 ]]; then
+        trap 'rc=$?; if [[ $rc -ne 0 ]]; then 
           touch /tmp/shared/exit;
         fi;
         cp -r /go/src/github.com/openshift/openshift-azure/_data /tmp/shared &>/dev/null
@@ -219,7 +221,7 @@ objects:
           export DNS_DOMAIN=osadev.cloud
           export DNS_RESOURCEGROUP=dns
           export KUBECONFIG=/tmp/shared/_data/_out/admin.kubeconfig
-
+  
           cp -r /tmp/shared/_data /go/src/github.com/openshift/openshift-azure/
           cd /go/src/github.com/openshift/openshift-azure/
           source /etc/azure/credentials/secret
