Add a fast forward script for release branches

diff --git a/hack/branch b/hack/branch
--- a/hack/branch
+++ b/hack/branch
@@ -23,7 +23,9 @@ for repo in `managed_repos "${BRANCH}"`; do
   if [[ ! -d ${DIR}/src/github.com/${repo} ]]; then
     mkdir -p ${DIR}/src/github.com/${repo}
     pushd ${DIR}/src/github.com/${repo} &>/dev/null
-    git clone --depth=1 --branch ${BRANCH} git@github.com:${repo} .
+    if ! git clone --depth=1 --branch ${BRANCH} git@github.com:${repo} $(pwd); then
+      echo "error: ${repo} is not a valid Git repository" 2>&1
+    fi
     popd &>/dev/null
   fi
 done
@@ -36,6 +38,37 @@ if [[ "${1-}" == "bump" ]]; then
     git fetch origin ${BRANCH} 2>/dev/null
     git reset --hard origin/${BRANCH} >/dev/null
     echo date '+%Y%m%d-%H%M%S' > .repo-date; git add .repo-date; git commit -S -m "Updating branch ${BRANCH}"
+    popd &>/dev/null
+  done
+  exit 0
+fi
+
+# create a commit in each repo
+if [[ "${1-}" == "fast-forward" ]]; then
+  if [[ -z "${TO-}"  ]]; then
+    echo "Must set TO= to the major/minor version of the release to fast-forward"
+    exit 1
+  fi
+  TO_BRANCH=release-${TO}
+  for repo in `managed_repos "${TO_BRANCH}"`; do
+    echo "${repo}"
+    pushd ${DIR}/src/github.com/${repo} &>/dev/null
+    if ! git fetch origin --deepen=300 --update-shallow -n -f ${TO_BRANCH}:remotes/origin/${TO_BRANCH} ${BRANCH}:remotes/origin/${BRANCH} &>/dev/null; then
+      echo "error: ${repo} does not have a ${TO_BRANCH} branch" 2>&1
+      continue
+    fi
+    if ! git rev-parse --verify ${TO_BRANCH} &>/dev/null; then
+      git branch ${TO_BRANCH} origin/${TO_BRANCH}
+    fi
+    git checkout ${TO_BRANCH} &>/dev/null
+    git reset --hard origin/${TO_BRANCH} &>/dev/null
+    if ! git pull --ff-only --ff origin ${BRANCH} &>/dev/null; then
+      echo "error: ${repo} cannot fast-forward ${TO_BRANCH} cleanly from master" 2>&1
+      continue
+    fi
+    git --no-pager log --oneline origin/${TO_BRANCH}..${TO_BRANCH}
+    # TODO: for safety comment this out most of the time
+    # git push origin "${TO_BRANCH}"
     popd &>/dev/null
   done
   exit 0
@@ -60,29 +93,42 @@ if [[ "${1-}" == "reset" ]]; then
   exit 0
 fi
 
-if [[ -z "${FROM-}" ]]; then
-	echo "Must set FROM= to the major/minor version of the current release, e.g. 3.9"
-  exit 1
-fi
-if [[ -z "${TO-}" ]]; then
-  echo "Must set TO= to the major/minor version of the next release, e.g. 3.10"
-  exit 1
-fi
-
+out=""
 for repo in `managed_repos "${BRANCH}"`; do
   pushd ${DIR}/src/github.com/${repo} &>/dev/null
 
-  if [[ "${1-}" == "" ]]; then
-    echo ${repo} '|' $( git log --oneline -1 HEAD )
+  if ! git rev-parse HEAD &>/dev/null; then
+    echo "error: ${repo} is not a git directory" 2>&1
     continue
   fi
 
+  if [[ "${1-}" == "" ]]; then
+    out+="${repo}|$( git log --relative-date --pretty='%cd|%h|%s' -1 origin/${BRANCH} -- || true )\n"
+    continue
+  fi
+
+  if [[ -z "${FROM-}" ]]; then
+    echo "Must set FROM= to the major/minor version of the current release, e.g. 3.9"
+    exit 1
+  fi
+
   if [[ "${1-}" == "create" ]]; then
-    if ! git rev-parse release-${FROM} &>/dev/null; then
-      git checkout -b release-${FROM} ${BRANCH}
+    if git rev-parse release-${FROM} &>/dev/null; then
+      continue
     fi
+    git checkout -b release-${FROM} ${BRANCH}
     git push origin "release-${FROM}"
     continue
+  fi
+
+  if [[ "${1-}" != "push" && "${1-}" != "try" ]]; then
+    echo "Must set argument to 'push' or 'try' to continue"
+    exit 1
+  fi
+
+  if [[ -z "${TO-}" ]]; then
+    echo "Must set TO= to the major/minor version of the next release, e.g. 3.10"
+    exit 1
   fi
 
   if git rev-parse release-${FROM} &>/dev/null; then
@@ -105,4 +151,4 @@ for repo in `managed_repos "${BRANCH}"`; do
 
   popd &>/dev/null
 done
-
+echo $out | column -ts '|'
