argh

diff --git a/ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.19.yaml b/ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.19.yaml
--- a/ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.19.yaml
+++ b/ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.19.yaml
@@ -169,41 +169,52 @@ tests:
     workflow: openshift-e2e-vsphere-ccm-ovn-hybrid-install
 - as: 4-19-4-20-upgrade
   cron: 0 9 * * 1
-  workflow: ipi-azure-ovn-hybrid
   steps:
     cluster_profile: azure-2
     test:
       - as: install
         cli: latest
-        from: operator-sdk
-        resources:
-          requests:
-            cpu: 1000m
-            memory: 400Mi
         dependencies:
           - env: PREVIOUS_BUNDLE
             name: previous-bundle
           - env: PREVIOUS_OPERATOR
             name: previous-wmco
         commands: |
-          export KUBECONFIG=${KUBECONFIG:-/tmp/kubeconfig}
           export WMCO_NS=openshift-windows-machine-config-operator
-          oc create namespace $WMCO_NS || echo "Namespace exists"
-          operator-sdk run bundle --timeout=15m --security-context-config restricted -n $WMCO_NS "$PREVIOUS_BUNDLE"
-          oc get csv -n $WMCO_NS | awk '{print $1}' | tail -n1 | xargs oc patch csv -n $WMCO_NS --type='json' \
-            -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/0/image", "value": "'"$PREVIOUS_OPERATOR"'"}]'
+          oc create namespace $WMCO_NS
+          oc label --overwrite=true ns $WMCO_NS openshift.io/cluster-monitoring=true \
+          pod-security.kubernetes.io/enforce=privileged
+          # Deploy the bundle which will fail to come up due to it pointing to the operator image via a tag that is only
+          # available to the presubmit job it is created within. This pipeline image is removed shortly after said job
+          # completes, so the csv needs to be patched to point the equivalent image that has been promoted.
+          operator-sdk run bundle --timeout=15m --security-context-config restricted -n $WMCO_NS "$PREVIOUS_BUNDLE" \
+          || oc get csv -n $WMCO_NS |awk {'print $1'} | tail -n1 | xargs oc patch csv -n $WMCO_NS --type='json' \
+          -p="[{\"op\": \"replace\", \"path\": \"/spec/install/spec/deployments/0/spec/template/spec/containers/0/image\", \"value\": \"$PREVIOUS_OPERATOR\"}]"
           sleep 10
+          # Delete the deployment which will then be recreated by the subscription controller with the correct image
+          oc delete deployment -n $WMCO_NS windows-machine-config-operator
+          # oc wait will immediately fail if the deployment does not exist yet, first retry until the deployment is
+          # created by the subscription controller
           retries=0
-          while ! oc get deployment -n $WMCO_NS windows-machine-config-operator; do
+          while ! oc get -n $WMCO_NS deployment windows-machine-config-operator; do
             if [[ $retries -eq 10 ]]; then
-              echo "Deployment did not appear"
+              echo max retries hit
               exit 1
             fi
             sleep 1m
             retries=$((retries+1))
           done
           oc wait --timeout=10m --for condition=Available -n $WMCO_NS deployment windows-machine-config-operator
-
+        dependencies:
+          - env: PREVIOUS_BUNDLE
+            name: previous-bundle
+          - env: PREVIOUS_OPERATOR
+            name: previous-wmco
+        from: operator-sdk
+        resources:
+          requests:
+            cpu: 1000m
+            memory: 400Mi
       - as: test-setup
         cli: latest
         from: windows-machine-config-operator-test
@@ -264,6 +275,7 @@ tests:
             memory: 400Mi
         commands: |
           make upgrade-test
+  workflow: ipi-azure-ovn-hybrid
   timeout: 5h0m0s
 - always_run: false
   as: azure-e2e-upgrade
