Add kubevirt hypershift csi periodic jobs 4.14 and 4.15
Add new periodic jobs for kubevirt csi running on hypershift

Signed-off-by: Alexander Wels <awels@redhat.com>

diff --git a/ci-operator/step-registry/hypershift/kubevirt/run-csi-e2e/hypershift-kubevirt-run-csi-e2e-chain.yaml b/ci-operator/step-registry/hypershift/kubevirt/run-csi-e2e/hypershift-kubevirt-run-csi-e2e-chain.yaml
--- a/ci-operator/step-registry/hypershift/kubevirt/run-csi-e2e/hypershift-kubevirt-run-csi-e2e-chain.yaml
+++ b/ci-operator/step-registry/hypershift/kubevirt/run-csi-e2e/hypershift-kubevirt-run-csi-e2e-chain.yaml
@@ -20,7 +20,19 @@ chain:
       openshift-tests run openshift/csi ${TEST_ARGS:-} \
         --provider "${TEST_PROVIDER}" \
         -o "${ARTIFACT_DIR}/e2e.log" \
-        --junit-dir "${ARTIFACT_DIR}/junit"
+        --junit-dir "${ARTIFACT_DIR}/junit" 2>&1 | tee /tmp/openshift-csi-tests.log
+
+      csi_exit_code=${PIPESTATUS[0]}
+
+      # If this line is shown in the openshift-tests output, all of the conformance test cases passed,
+      # but the monitor test has failed. Currently we're ignoring MonitorTest failures until we resolve:
+      # https://issues.redhat.com/browse/CNV-33717
+      if [[ -n "${SKIP_MONITOR_TEST}" ]] && [[ $(grep "failed due to a MonitorTest failure" /tmp/openshift-csi-tests.log) ]];
+      then
+        echo "overriding Monitor Test Failure in CSI tests"
+        csi_exit_code=0
+      fi
+      exit ${csi_exit_code}
     timeout: 14400s
     env:
     - name: TEST_ARGS
