vSphere UPI: bootstrap DNS entries remain after IP deleted from IPAM
Temporarily remove the deletion of bootstrap virtual machine and IPAM
records. Will be delete at teardown.

While testing I noticed that in some instances the `oc get csr`
silently fails.  add `|| true`.

diff --git a/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml b/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
--- a/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
+++ b/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
@@ -2102,8 +2102,12 @@ objects:
           gsutil rb gs://${INFRA_ID}-bootstrap-ignition
           gcloud deployment-manager deployments delete -q ${CLUSTER_NAME}-bootstrap
         elif [[ "${CLUSTER_TYPE}" == "vsphere" ]]; then
-          terraform destroy -auto-approve -target module.bootstrap -no-color &
-          wait "$!"
+          # To ease debugging of ip address use
+          host -t A "api.${CLUSTER_NAME}.${base_domain}"
+          # Bootstrap is removed and the IPAM entry is also removed.  DNS is not updated.
+          # Since the ip address has been released it will be used in another cluster.
+          # Until an alternative solution can be found do not delete bootstrap.
+          #terraform destroy -auto-approve -target module.bootstrap -no-color &
         elif [[ "${CLUSTER_TYPE}" == "azure4" ]]; then
           az network nsg rule delete -g $RESOURCE_GROUP --nsg-name ${INFRA_ID}-controlplane-nsg --name bootstrap_ssh_in
           az vm stop -g $RESOURCE_GROUP --name ${INFRA_ID}-bootstrap
@@ -2136,7 +2140,8 @@ objects:
         function approve_csrs() {
           while true; do
             if [[ ! -f /tmp/install-complete ]]; then
-              oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs --no-run-if-empty oc adm certificate approve
+              # even if oc get csr fails continue
+              oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs --no-run-if-empty oc adm certificate approve || true
               sleep 15 & wait
               continue
             else
