templates/e2e-metal: fix faulty retry for creating infra resources
Packet returns transients errors when creating devices.
example, `Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble.`
therefore the terraform apply needs to be retried a few time before giving up.

Previously the retry logic retried on failure but after max retires it would continue to next step. Failing beyond max retries should be fatal

diff --git a/ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml b/ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
--- a/ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
+++ b/ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
@@ -285,7 +285,13 @@ objects:
 
         echo "Creating resources using terraform"
         (cd /tmp/artifacts/terraform && terraform init)
-        for r in {1..3}; do (cd /tmp/artifacts/terraform && terraform apply -auto-approve) && break ; done
+
+        # Packet returns transients errors when creating devices.
+        # example, `Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble.`
+        # therefore the terraform apply needs to be retried a few time before giving up.
+        rc=1
+        for r in {1..5}; do (cd /tmp/artifacts/terraform && terraform apply -auto-approve) && rc=0 && break ; done
+        if test "${rc}" -eq 1; then echo "failed to create the infra resources"; exit 1; fi
 
         echo "Waiting for bootstrap to complete"
         openshift-install --dir=/tmp/artifacts/installer wait-for bootstrap-complete
