Reintegrate changes for gcp nested-virt into custom-test-image
Moves the reprovisioning that was originally done in the test.sh
script in kubevirt/kubevirt into the custom-test-image template
Adds settings to optionally enable it and select a nested virt
image.
kubevirt/kubevirt prow job is updated accordingly.

Signed-off-by: Daniel Hiller <daniel.hiller.1972@gmail.com>

diff --git a/ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml b/ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
--- a/ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
+++ b/ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
@@ -19,6 +19,12 @@ parameters:
   required: true
 - name: CLUSTER_TYPE
   required: true
+- name: CLUSTER_ENABLE_NESTED_VIRT
+  value: "false"
+  required: false
+- name: CLUSTER_NESTED_VIRT_IMAGE
+  value: "rhcos43-nested-virt"
+  required: false
 - name: TEST_COMMAND
   required: true
 - name: RELEASE_IMAGE_LATEST
@@ -227,6 +233,7 @@ objects:
             exit 1
           fi
           if [[ ! -f /tmp/shared/setup-success ]]; then
+            echo "Waiting for setup to finish..."
             sleep 15 & wait
             continue
           fi
@@ -335,7 +342,7 @@ objects:
       terminationMessagePolicy: FallbackToLogsOnError
       volumeMounts:
       - name: shared-tmp
-        mountPath: /tmp
+        mountPath: /tmp/shared
       - name: cluster-profile
         mountPath: /etc/openshift-installer
       - name: artifacts
@@ -384,8 +391,24 @@ objects:
         #!/bin/bash
         set -euo pipefail
 
-        trap 'rc=$?; if test "${rc}" -eq 0; then touch /tmp/setup-success; else touch /tmp/exit /tmp/setup-failed; fi; exit "${rc}"' EXIT
+        trap 'rc=$?; if test "${rc}" -eq 0; then touch /tmp/shared/setup-success; else touch /tmp/shared/exit /tmp/shared/setup-failed; fi; exit "${rc}"' EXIT
         trap 'CHILDREN=$(jobs -p); if test -n "${CHILDREN}"; then kill ${CHILDREN} && wait; fi' TERM
+
+        if [[ "${CLUSTER_TYPE}" != "gcp" ]] && [[ "${CLUSTER_ENABLE_NESTED_VIRT-false}" == "true" ]]; then
+            echo "CLUSTER_ENABLE_NESTED_VIRT is unsupported for cluster type '${CLUSTER_TYPE}'"
+            exit 1
+        fi
+
+        export PATH=/tmp/shared:$PATH  # gain access to oc
+        while ! command -V oc; do sleep 1; done # poll to make sure that the test container has dropped oc into the shared volume
+
+        # we need jq for later machine rescaling
+        (cd /tmp/shared && curl -L -o jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x jq)
+        if ! command -V jq; then
+            echo "Failed to fetch jq"
+            exit 1
+        fi
+
         cp "$(command -v openshift-install)" /tmp
         mkdir /tmp/artifacts/installer
 
@@ -393,8 +416,6 @@ objects:
           echo "Installing from initial release ${RELEASE_IMAGE_INITIAL}"
           OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="${RELEASE_IMAGE_INITIAL}"
         elif [[ "${CLUSTER_VARIANT}" =~ "mirror" ]]; then
-          export PATH=$PATH:/tmp/shared  # gain access to oc
-          while [ ! command -V oc ]; do sleep 1; done # poll to make sure that the test container has dropped oc into the shared volume
 
           # mirror the release image and override the release image to point to the mirrored one
           mkdir /tmp/.docker && cp /etc/openshift-installer/pull-secret /tmp/.docker/config.json
@@ -631,6 +652,41 @@ objects:
 
         TF_LOG=debug openshift-install --dir=/tmp/artifacts/installer create cluster 2>&1 | grep --line-buffered -v password &
         wait "$!"
+
+        if [[ "${CLUSTER_TYPE}" == "gcp" ]] && [[ "${CLUSTER_ENABLE_NESTED_VIRT-false}" == "true" ]]; then
+          ### enable nested-virt ###
+          export KUBECONFIG=/tmp/artifacts/installer/auth/kubeconfig
+          oc get machineset -n openshift-machine-api -o json >/tmp/machinesets.json
+          MACHINE_IMAGE=$(jq -r .items[0].spec.template.spec.providerSpec.value.disks[0].image /tmp/machinesets.json)
+          sed -i 's/'"$MACHINE_IMAGE"'/'"$CLUSTER_NESTED_VIRT_IMAGE"'/g' /tmp/machinesets.json
+          oc apply -f /tmp/machinesets.json
+          oc scale --replicas=0 machineset --all -n openshift-machine-api
+          oc get machines -n openshift-machine-api -o json >/tmp/machines.json
+          num_machines=$(jq '.items | length' /tmp/machines.json)
+          while [ "$num_machines" -ne "3" ]; do
+            sleep 5
+            oc get machines -n openshift-machine-api -o json >/tmp/machines.json
+            num_machines=$(jq '.items | length' /tmp/machines.json)
+          done
+          oc scale --replicas=1 machineset --all -n openshift-machine-api
+          while [ "$num_machines" -ne "6" ]; do
+            sleep 5
+            oc get machines -n openshift-machine-api -o json >/tmp/machines.json
+            num_machines=$(jq '.items | length' /tmp/machines.json)
+          done
+          while [ $(oc get nodes | wc -l) -ne "7" ]; do oc get nodes; sleep 5; done
+          nodes_ready=false
+          while ! "$nodes_ready"; do sleep 5 && if ! oc get nodes | grep NotReady; then nodes_ready=true; fi; done
+          oc project default
+
+          # apply kvm device plugin
+          oc apply -f https://raw.githubusercontent.com/kubevirt/kubernetes-device-plugins/master/manifests/kvm-ds.yml
+          workers=$(oc get nodes | grep worker | awk '{ print $1 }')
+          workers_each=($workers)
+          for i in {0..2}; do
+            if ! oc debug node/"${workers_each[i]}" -- ls /dev/kvm; then oc debug node/"${workers_each[i]}" -- ls /dev/kvm; fi
+          done
+        fi
 
     # Performs cleanup of all created resources
     - name: teardown
