Added rhcos downloading script
- Code clean up
- Added function to make sure teardwon container is up before starting test.

diff --git a/ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml b/ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
--- a/ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
+++ b/ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
@@ -22,8 +22,8 @@ parameters:
   value: openstack-cloud
 - name: OPENSTACK_EXTERNAL_NETWORK
   value: external
-- name: OPENSTACK_IMAGE
-  value: rhcos-44.81.202003062006
+- name: RHCOS_RELEASE
+  value: master
 - name: OPENSTACK_REGION
   value: moc-kzn
 - name: OPENSTACK_FLAVOR
@@ -157,8 +157,6 @@ objects:
         value: ${RELEASE_IMAGE_LATEST}
       - name: OPENSHIFT_INSTALL_INVOKER
         value: openshift-internal-ci/${JOB_NAME_SAFE}/${BUILD_ID}
-      - name: OPENSTACK_IMAGE
-        value: ${OPENSTACK_IMAGE}
       - name: OPENSTACK_REGION
         value: ${OPENSTACK_REGION}
       - name: OPENSTACK_FLAVOR
@@ -206,6 +204,8 @@ objects:
         value: ${NUMBER_OF_MASTERS}
       - name: NUMBER_OF_WORKERS
         value: ${NUMBER_OF_WORKERS}
+      - name: RHCOS_RELEASE
+        value: ${RHCOS_RELEASE}
 
       command:
       - /bin/sh
@@ -216,14 +216,6 @@ objects:
         # configure pipefail to return value from last non-zero exiting process or children
         set -euo pipefail
 
-        function debug_stop() {
-          while [[ ! -f ${TMP_SHARED}/$1 ]]
-            do
-            echo "waiting for ${TMP_SHARED}/$1"
-            sleep 60
-          done
-        }
-
         #Before we can do anything on the container we need to make sure our user has the approriate permissions.
         function allow_user_access() {
           if ! whoami &> /dev/null; then
@@ -232,6 +224,34 @@ objects:
             fi
           fi
           mkdir -p "${HOME}"
+        }
+
+        function upload_rhcos_image() {
+          export RHCOS_GLANCE_IMAGE_NAME=${INFRA_ID}-rhcos-${RHCOS_RELEASE}
+          rm -rf rhcos.json
+          local IMAGE_SOURCE=https://raw.githubusercontent.com/openshift/installer/${RHCOS_RELEASE}/data/data/rhcos.json
+          wget -q -O rhcos.json $IMAGE_SOURCE
+          local GZ_IMAGE_FILENAME=$(grep path rhcos.json | grep openstack |awk '{print $2}' | awk -F\" '{print $2}')
+          local BASEURI=$(grep base rhcos.json | awk '{print $2}' |awk -F\" '{print $2}')
+          wget  -q -O ${TMP_SHARED}/$GZ_IMAGE_FILENAME $BASEURI$GZ_IMAGE_FILENAME
+          gunzip ${TMP_SHARED}/$GZ_IMAGE_FILENAME
+          local IMAGE_FILENAME=${GZ_IMAGE_FILENAME%.gz}
+          IMAGE_ID=$(openstack image create --container-format=bare --disk-format=qcow2 --file ${TMP_SHARED}/$IMAGE_FILENAME $RHCOS_GLANCE_IMAGE_NAME -f value -c id)
+          echo $IMAGE_ID > ${TMP_SHARED}/RHCOS_GLANCE_IMAGE_ID
+        }
+
+        function wait_for_teardown_container(){
+          filename=${TMP_SHARED}/teardown_running
+          echo "Waiting for teardown container to start"
+          for i in $(seq 1 150); do
+            echo looking for $filename
+            if [[ -f $filename ]]; then
+              return 0
+            fi
+            sleep 2
+          done
+          echo "Teardown container is not running after 5 minutes. Test can't start"
+          exit 1
         }
 
         function check_os_quotas() {
@@ -280,14 +300,6 @@ objects:
           fi
         }
 
-        function announce_cluster_status() {
-          if test -n "${BOOTSTRAP_SUCCESFULL}"; then
-            touch ${TMP_SHARED}/cluster-deployed
-          else:
-            touch ${TMP_SHARED}/cluster-not-deployed
-          fi
-        }
-
         function signal_setup_complete() {
           touch ${TMP_SHARED}/setup-complete
         }
@@ -298,10 +310,6 @@ objects:
           # We will remove "ci-op-" prefix from there to keep just last 14 characters. and it cannot start with a "-"
           UNSAFE_CLUSTER_NAME=${CLUSTER_NAME:${#CLUSTER_NAME}<14?0:-14}
           export CLUSTER_NAME=${UNSAFE_CLUSTER_NAME#"-"}
-
-          #initialize control variables
-          GATHER_BOOTSTRAP_ARGS=
-          BOOTSTRAP_SUCCESFULL=
 
           # copy active openshift-install binary to ${TMP_SHARED}
           cp "$(command -v openshift-install)" ${TMP_SHARED}
@@ -329,7 +337,6 @@ objects:
         }
 
         function get_bootstrap_fip() {
-          export INFRA_ID=$(sed -n 's|.*"infraID":"\([^"]*\)".*|\1|p' ${ASSETS_DIR}/metadata.json )
           export BOOTSTRAP_HOSTNAME=${INFRA_ID}-bootstrap
           export BOOTSTRAP_FIP=$(openstack server list --name $BOOTSTRAP_HOSTNAME -f value -c Networks | awk '{print $2}')
           echo $BOOTSTRAP_FIP
@@ -519,9 +526,9 @@ objects:
 
           # upload bootstrap.ign to glance
           BOOTSTRAP_IGN_PATH=${ASSETS_DIR}/bootstrap.ign
-          GLANCE_IMAGE_ID=$(openstack image create --disk-format raw --container-format bare --file ${BOOTSTRAP_IGN_PATH} ${INFRA_ID}-bootstrap-ignition | grep " id " | awk '{print $4}')
-          echo $GLANCE_IMAGE_ID > ${TMP_SHARED}/GLANCE_IMAGE_ID
-          FILE_LOCATION=$(openstack image show ${GLANCE_IMAGE_ID} | grep -oh "\/.*file")
+          GLANCE_SHIM_IMAGE_ID=$(openstack image create --disk-format raw --container-format bare --file ${BOOTSTRAP_IGN_PATH} ${INFRA_ID}-bootstrap-ignition -f value -c id)
+          echo $GLANCE_SHIM_IMAGE_ID > ${TMP_SHARED}/GLANCE_SHIM_IMAGE_ID
+          FILE_LOCATION=$(openstack image show ${GLANCE_SHIM_IMAGE_ID} | grep -oh "\/.*file")
           GLANCE_ADDRESS=$(openstack catalog show glance -f table -c endpoints  | grep public | awk '{print $4}')
           export GLANCE_IMAGE_URL="$GLANCE_ADDRESS$FILE_LOCATION"
 
@@ -613,7 +620,7 @@ objects:
           sed -i "s~os_subnet_range.*~os_subnet_range: \'${OS_SUBNET_RANGE}\'~g" ${OS_UPI_DIR}/inventory.yaml
           sed -i "s/os_flavor_master.*/os_flavor_master: \'${OPENSTACK_FLAVOR}\'/g" ${OS_UPI_DIR}/inventory.yaml
           sed -i "s/os_flavor_worker.*/os_flavor_worker: \'${OPENSTACK_FLAVOR}\'/g" ${OS_UPI_DIR}/inventory.yaml
-          sed -i "s/os_image_rhcos.*/os_image_rhcos: \'${OPENSTACK_IMAGE}\'/g" ${OS_UPI_DIR}/inventory.yaml
+          sed -i "s/os_image_rhcos.*/os_image_rhcos: \'${RHCOS_GLANCE_IMAGE_NAME}\'/g" ${OS_UPI_DIR}/inventory.yaml
           sed -i "s/os_external_network.*/os_external_network: \'${OPENSTACK_EXTERNAL_NETWORK}\'/g" ${OS_UPI_DIR}/inventory.yaml
           sed -i "s/os_api_fip.*/os_api_fip: \'${LB_FIP_IP}\'/g" ${OS_UPI_DIR}/inventory.yaml
           sed -i "s/os_ingress_fip.*/os_ingress_fip: \'${INGRESS_FIP_IP}\'/g" ${OS_UPI_DIR}/inventory.yaml
@@ -722,7 +729,7 @@ objects:
           gather_bootstrap_logs
           mv ${TMP_SHARED}/BOOTSTRAP_FIP ${TMP_SHARED}/BOOTSTRAP_FIP_logs_collected
           ansible-playbook -i "${OS_UPI_DIR}/inventory.yaml" "${OS_UPI_DIR}/down-bootstrap.yaml"
-          openstack image delete $GLANCE_IMAGE_ID
+          openstack image delete $GLANCE_SHIM_IMAGE_ID
         }
 
         function deploy_compute_nodes() {
@@ -737,7 +744,7 @@ objects:
 
         function approve_csrs() {
           while true; do
-            if [[ ! -f ${TMP_SHARED}/cluster-deployed ]]; then
+            if [[ ! -f ${TMP_SHARED}/setup-complete ]]; then
               oc get csr -o name | xargs oc adm certificate approve
               sleep 15 & wait
               continue
@@ -761,9 +768,10 @@ objects:
         }
 
 
-        # Test execution
+        # Test setup
         trap  clean_exit EXIT
         trap clean_term  TERM
+        wait_for_teardown_container
         allow_user_access
         setup_test_bed
         check_early_failures
@@ -775,16 +783,14 @@ objects:
         backup_install_config
         create_manifest_files
         create_ignition_configs_and_jsons
+        upload_rhcos_image
         prepair_ansible_playbooks_workspace
         verify_playbooks_status
         run_bootstrap_playbooks
         run_control_plane_playbooks
         wait_for_control_plane
         verify_dns_resolvs
-
         wait_for_bootstrap_complete
-        #Test currently failing here
-
         access_the_openshiftapi
         delete_bootstrap_resources
         deploy_compute_nodes
@@ -792,7 +798,6 @@ objects:
         approve_csrs_in_background
         wait_for_install_complete
         check_os_quotas
-        announce_cluster_status
         signal_setup_complete
 
 
@@ -1236,9 +1241,15 @@ objects:
         }
 
         function delete_glance_shim_image() {
-          GLANCE_IMAGE_ID=`cat ${TMP_SHARED}/GLANCE_IMAGE_ID`
-          echo "Deleting glance image $GLANCE_IMAGE_ID"
-          openstack image delete $GLANCE_IMAGE_ID
+          GLANCE_SHIM_IMAGE_ID=`cat ${TMP_SHARED}/GLANCE_SHIM_IMAGE_ID`
+          echo "Deleting glance image $GLANCE_SHIM_IMAGE_ID"
+          openstack image delete $GLANCE_SHIM_IMAGE_ID
+        }
+
+        function delete_glance_rhcos_image() {
+          GLANCE_RHCOS_IMAGE_ID=`cat ${TMP_SHARED}/GLANCE_RHCOS_IMAGE_ID`
+          echo "Deleting rhcos glance image ${GLANCE_RHCOS_IMAGE_ID}"
+          openstack image delete ${GLANCE_RHCOS_IMAGE_ID}
         }
 
         function verify_teardown_playbooks() {
@@ -1285,12 +1296,8 @@ objects:
           done
         }
 
-        function debug_stop() {
-          while [[ ! -f ${TMP_SHARED}/$1 ]]
-            do
-            echo "waiting for ${TMP_SHARED}/$1"
-            sleep 60
-          done
+        function signal_teardown_container_is_running(){
+          touch ${TMP_SHARED}/teardown_running
         }
 
         function teardown() {
@@ -1306,6 +1313,7 @@ objects:
           delete_api_fip
           delete_ingress_fip
           delete_glance_shim_image
+          delete_glance_rhcos_image
           verify_teardown_playbooks
           destroy_cluster
           run_teardown_playbooks
@@ -1320,6 +1328,7 @@ objects:
         trap 'teardown' EXIT
         trap 'jobs -p | xargs -r kill || true; exit 0' TERM
 
+        signal_teardown_container_is_running
         allow_user_access
         wait_for_other_containers_to_exit
 
