Add VSphere IPI to e2e template.
Adds VSphere IPI as an option for e2e template:
- template reserves virtual IPs required for vsphere install
- teardown removes virtual IPs
- update installer presubmit job
- rename upi job in installer repo to have -upi postfix, following upi convention.

diff --git a/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml b/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
--- a/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
+++ b/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
@@ -1133,6 +1133,78 @@ objects:
           rm -f /tmp/artifacts/installer/openshift/99_openshift-cluster-api_master-machines-*.yaml
           rm -f /tmp/artifacts/installer/openshift/99_openshift-cluster-api_worker-machineset-*.yaml
           sed -i "s;mastersSchedulable: true;mastersSchedulable: false;g" /tmp/artifacts/installer/manifests/cluster-scheduler-02-config.yml
+        #DEBUG TODO Come up with better conditional
+        #elif [[ "${CLUSTER_TYPE}" == "vsphere" ]]; then
+        elif [[ "${JOB_NAME_SAFE}" == "e2e-vsphere-ipi" ]]; then
+            echo "DEBUG REMOVE ME installing vsphere cluster"
+            base_domain="${BASE_DOMAIN:-origin-ci-int-aws.dev.rhcloud.com}"
+            echo "DEBUG REMOVE ME base_domain ${base_domain}"
+            vsphere_user=$(grep -oP 'vsphere_user="\K[^"]+' ${TFVARS_PATH})
+            echo "DEBUG REMOVE ME vsphere_user ${vsphere_user}"
+            vsphere_password=$(grep -oP 'vsphere_password="\K[^"]+' ${TFVARS_PATH})
+            echo "DEBUG REMOVE ME vsphere_password"
+            #ipam=$(grep -oP 'ipam="\K[^"]+' ${TFVARS_PATH})
+            ipam="139.178.89.254"
+            echo "DEBUG REMOVE ME ipam ${ipam}"
+            #ipam_token=$(grep -oP 'ipam_token="\K[^"]+' ${TFVARS_PATH})
+            ipam_token="test"
+            echo "DEBUG REMOVE ME ipam_token"
+
+            # FIXME: get epel-release or otherwise add awscli to our UPI image
+            export PATH="${HOME}/.local/bin:${PATH}"
+            easy_install --user pip  # our Python 2.7.5 is even too old for ensurepip
+            pip install --user awscli
+            export AWS_DEFAULT_REGION="${AWS_REGION}"  # CLI prefers the former
+
+            declare -a vips
+            echo "DEBUG REMOVE ME about to reserve ip addresses"
+            for i in {0..2}
+            do
+              echo "DEBUG REMOVE ME reserving IP addresses"
+              args="{"network":"139.178.87.128","hostname":"$CLUSTER_NAME-$i","ipam":"$ipam","ipam_token":"$ipam_token"}"
+              vips[$i]=$(echo $args | bash <(curl -s https://raw.githubusercontent.com/openshift/installer/master/upi/vsphere/machine/cidr_to_ip.sh))
+              if [[ -z ${vips[$i]} ]]; then
+                echo "error: Unable to reserve virtual IP address, exiting" 1>&2
+                exit 1
+              fi
+            done
+
+            api_vip=${vips[0]}
+            ingress_vip=${vips[1]}
+            dns_vip=${vips[2]}
+
+            echo "DEBUG REMOVE ME writing install config"
+            cat > /tmp/artifacts/installer/install-config.yaml << EOF
+        apiVersion: v1
+        baseDomain: ${base_domain}
+        metadata:
+          name: ${CLUSTER_NAME}
+        controlPlane:
+          name: master
+          replicas: 3
+        compute:
+        - name: worker
+          replicas: ${workers}
+        networking:
+          machineCIDR: 139.178.87.128/25
+        platform:
+          vsphere:
+            vCenter: vcsa-ci.vmware.devcluster.openshift.com
+            username: ${vsphere_user}
+            password: ${vsphere_password}
+            cluster: devel
+            datacenter: dc1
+            defaultDatastore: nvme-ds1
+            network: VM Network
+            apiVIP: ${api_vip}
+            ingressVIP: ${ingress_vip}
+            dnsVIP: ${dns_vip}
+        pullSecret: >
+          ${PULL_SECRET}
+        sshKey: |
+          ${SSH_PUB_KEY}
+        EOF
+          echo "DEBUG REMOVE ME created install config"
         elif [[ "${CLUSTER_TYPE}" == "vsphere" ]]; then
             base_domain="${BASE_DOMAIN:-origin-ci-int-aws.dev.rhcloud.com}"
             # Get user and password from TFVARS_PATH
@@ -1244,7 +1316,7 @@ objects:
             sed -i "/publicZone/,+1d" manifests/cluster-dns-02-config.yml 
             sed -i "/privateZone/,+1d" manifests/cluster-dns-02-config.yml 
 
-            popd
+            popd        
         else
             echo "Unsupported cluster type '${CLUSTER_TYPE}'"
             exit 1
