separated CLUSTER_NETWORK_MANIFEST and rt variant flows
Signed-off-by: Marc Sluiter <msluiter@redhat.com>

diff --git a/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml b/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
--- a/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
+++ b/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
@@ -736,15 +736,18 @@ objects:
         fi
 
         # TODO: Replace with a more concise manifest injection approach
-        if [[ -n "${CLUSTER_NETWORK_MANIFEST:-}" ]] || has_variant "rt"; then
+        if [[ -n "${CLUSTER_NETWORK_MANIFEST:-}" ]]; then
             openshift-install --dir=/tmp/artifacts/installer/ create manifests
+            echo "${CLUSTER_NETWORK_MANIFEST}" > /tmp/artifacts/installer/manifests/cluster-network-03-config.yml
+        fi
 
-            if [[ -n "${CLUSTER_NETWORK_MANIFEST:-}" ]]; then
-              echo "${CLUSTER_NETWORK_MANIFEST}" > /tmp/artifacts/installer/manifests/cluster-network-03-config.yml
-            fi
-
-            if has_variant "rt"; then
-              cat > /tmp/artifacts/installer/manifests/realtime-worker-machine-config.yml << EOF
+        if has_variant "rt"; then
+          if [[ -n "${CLUSTER_NETWORK_MANIFEST:-}" ]]; then
+            echo 'error: CLUSTER_NETWORK_MANIFEST is incompatible with the `rt` variant'
+            exit 1
+          fi
+          openshift-install --dir=/tmp/artifacts/installer/ create manifests
+          cat > /tmp/artifacts/installer/manifests/realtime-worker-machine-config.yml << EOF
         apiVersion: machineconfiguration.openshift.io/v1
         kind: MachineConfig
         metadata:
@@ -754,7 +757,6 @@ objects:
         spec:
           kernelType: realtime
         EOF
-            fi
         fi
 
         TF_LOG=debug openshift-install --dir=/tmp/artifacts/installer create cluster 2>&1 | grep --line-buffered -v password &
