Adding estimator sidecar tests
Signed-off-by: Vishnu Challa <vchalla@vchalla-thinkpadp1gen2.rmtusnc.csb>

diff --git a/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml b/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
--- a/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
+++ b/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
@@ -113,6 +113,94 @@ tests:
     - chain: openshift-qe-node-density-heavy
     workflow: generic-claim
 - always_run: false
+  as: cluster-density-v2-kepler-estimator
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-estimator"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      USER_METADATA: layeredProduct=kepler-estimator
+    test:
+    - as: kepler-estimator
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
+  as: node-density-heavy-kepler-estimator
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-estimator"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATIONS_PER_NAMESPACE: "1"
+      NAMESPACED_ITERATIONS: "true"
+      PODS_PER_NODE: "200"
+      USER_METADATA: layeredProduct=kepler-estimator
+    test:
+    - as: kepler-estimator
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-node-density-heavy
+    workflow: generic-claim
+- always_run: false
   as: cluster-density-v2-no-kepler
   cluster_claim:
     architecture: amd64
@@ -160,4 +248,4 @@ zz_generated_metadata:
   branch: main
   org: openshift-power-monitoring
   repo: kepler
-  variant: ocp4.18-minimal-perfscale
+  variant: ocp4.18-perfscale
