Adding model server and full deployment models
Signed-off-by: Vishnu Challa <vchalla@vchalla-thinkpadp1gen2.rmtusnc.csb>

diff --git a/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml b/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
--- a/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
+++ b/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
@@ -41,6 +41,8 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=kepler-minimal
     test:
     - as: kepler-minimal
@@ -84,8 +86,10 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
       NAMESPACED_ITERATIONS: "true"
       PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=kepler-minimal
     test:
     - as: kepler-minimal
@@ -113,6 +117,54 @@ tests:
     - chain: openshift-qe-node-density-heavy
     workflow: generic-claim
 - always_run: false
+  as: mixed-workload-kepler-minimal
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-minimal", "mixedWorkload": "true"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      STRESS_NG_CPU_CORES: "1"
+      STRESS_NG_CPU_LOAD: "25"
+      USER_METADATA: layeredProduct=kepler-minimal,mixedWorkload=true
+    test:
+    - as: mixed-workload-kepler-minimal
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-stress-ng
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
   as: cluster-density-v2-kepler-estimator
   cluster_claim:
     architecture: amd64
@@ -129,6 +181,8 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=kepler-estimator
     test:
     - as: kepler-estimator
@@ -172,8 +226,10 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
       NAMESPACED_ITERATIONS: "true"
       PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=kepler-estimator
     test:
     - as: kepler-estimator
@@ -201,6 +257,337 @@ tests:
     - chain: openshift-qe-node-density-heavy
     workflow: generic-claim
 - always_run: false
+  as: mixed-workload-kepler-estimator
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-estimator", "mixedWorkload":
+        "true"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      STRESS_NG_CPU_CORES: "1"
+      STRESS_NG_CPU_LOAD: "25"
+      USER_METADATA: layeredProduct=kepler-estimator,mixedWorkload=true
+    test:
+    - as: mixed-workload-kepler-estimator
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-stress-ng
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
+  as: cluster-density-v2-kepler-model-server
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-model-server"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      USER_METADATA: layeredProduct=kepler-model-server
+    test:
+    - as: kepler-model-server
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
+  as: node-density-heavy-kepler-model-server
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-model-server"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      NAMESPACED_ITERATIONS: "true"
+      PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
+      USER_METADATA: layeredProduct=kepler-model-server
+    test:
+    - as: kepler-model-server
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-node-density-heavy
+    workflow: generic-claim
+- always_run: false
+  as: mixed-workload-kepler-model-server
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-model-server", "mixedWorkload":
+        "true"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      STRESS_NG_CPU_CORES: "1"
+      STRESS_NG_CPU_LOAD: "25"
+      USER_METADATA: layeredProduct=kepler-model-server,mixedWorkload=true
+    test:
+    - as: mixed-workload-kepler-model-server
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-stress-ng
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
+  as: cluster-density-v2-kepler-full-deployment
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-full-deployment"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      USER_METADATA: layeredProduct=kepler-full-deployment
+    test:
+    - as: kepler-full-deployment
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
+  as: node-density-heavy-kepler-full-deployment
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-full-deployment"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      NAMESPACED_ITERATIONS: "true"
+      PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
+      USER_METADATA: layeredProduct=kepler-full-deployment
+    test:
+    - as: kepler-full-deployment
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-node-density-heavy
+    workflow: generic-claim
+- always_run: false
+  as: mixed-workload-kepler-full-deployment
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-full-deployment", "mixedWorkload":
+        "true"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      STRESS_NG_CPU_CORES: "1"
+      STRESS_NG_CPU_LOAD: "25"
+      USER_METADATA: layeredProduct=kepler-full-deployment,mixedWorkload=true
+    test:
+    - as: mixed-workload-kepler-full-deployment
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-stress-ng
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
   as: cluster-density-v2-no-kepler
   cluster_claim:
     architecture: amd64
@@ -217,6 +604,8 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=no-kepler
     test:
     - chain: openshift-qe-cluster-density-v2
@@ -238,11 +627,39 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
       NAMESPACED_ITERATIONS: "true"
       PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=no-kepler
     test:
     - chain: openshift-qe-node-density-heavy
+    workflow: generic-claim
+- always_run: false
+  as: mixed-workload-no-kepler
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "no-kepler", "mixedWorkload": "true"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      STRESS_NG_CPU_CORES: "1"
+      STRESS_NG_CPU_LOAD: "25"
+      USER_METADATA: layeredProduct=no-kepler,mixedWorkload=true
+    test:
+    - chain: openshift-qe-stress-ng
+    - chain: openshift-qe-cluster-density-v2
     workflow: generic-claim
 zz_generated_metadata:
   branch: main
