Adding model server and full deployment models
Signed-off-by: Vishnu Challa <vchalla@vchalla-thinkpadp1gen2.rmtusnc.csb>

diff --git a/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml b/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
--- a/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
+++ b/ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
@@ -41,6 +41,8 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=kepler-minimal
     test:
     - as: kepler-minimal
@@ -84,8 +86,10 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
       NAMESPACED_ITERATIONS: "true"
       PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=kepler-minimal
     test:
     - as: kepler-minimal
@@ -129,6 +133,8 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=kepler-estimator
     test:
     - as: kepler-estimator
@@ -172,8 +178,10 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
       NAMESPACED_ITERATIONS: "true"
       PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=kepler-estimator
     test:
     - as: kepler-estimator
@@ -181,6 +189,190 @@ tests:
       commands: |
         GOFLAGS="" make tools
         GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-node-density-heavy
+    workflow: generic-claim
+- always_run: false
+  as: cluster-density-v2-kepler-model-server
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-model-server"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      USER_METADATA: layeredProduct=kepler-model-server
+    test:
+    - as: kepler-model-server
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
+  as: node-density-heavy-kepler-model-server
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-model-server"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      NAMESPACED_ITERATIONS: "true"
+      PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
+      USER_METADATA: layeredProduct=kepler-model-server
+    test:
+    - as: kepler-model-server
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-node-density-heavy
+    workflow: generic-claim
+- always_run: false
+  as: cluster-density-v2-kepler-full-deployment
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-full-deployment"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
+      USER_METADATA: layeredProduct=kepler-full-deployment
+    test:
+    - as: kepler-full-deployment
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY MODEL_SERVER_DEPLOY"
+        sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
+        oc apply -f _output/generated-manifest/deployment.yaml
+        echo "Validating Kepler Install"
+        oc rollout status -n kepler daemonset kepler-exporter --timeout 5m || {
+          oc get pods -n kepler
+          oc describe daemonset kepler-exporter -n kepler
+          echo "Kepler validation failed"
+        }
+        oc logs -n kepler daemonset/kepler-exporter
+      dependencies:
+      - env: EXPORTER_IMG
+        name: kepler
+      from: src
+      resources:
+        requests:
+          cpu: 200m
+          memory: 400Mi
+    - chain: openshift-qe-cluster-density-v2
+    workflow: generic-claim
+- always_run: false
+  as: node-density-heavy-kepler-full-deployment
+  cluster_claim:
+    architecture: amd64
+    cloud: aws
+    labels:
+      region: us-east-1
+    owner: obs-powermon
+    product: ocp
+    timeout: 4h0m0s
+    version: "4.18"
+  steps:
+    env:
+      ADDITIONAL_PARAMS: '{"layeredProduct": "kepler-full-deployment"}'
+      ENABLE_LOCAL_INDEX: "true"
+      EXTRA_FLAGS: --churn-duration=20m
+      ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      NAMESPACED_ITERATIONS: "true"
+      PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
+      USER_METADATA: layeredProduct=kepler-full-deployment
+    test:
+    - as: kepler-full-deployment
+      cli: latest
+      commands: |
+        GOFLAGS="" make tools
+        GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY MODEL_SERVER_DEPLOY"
         sed -i 's/namespace: monitoring/namespace: openshift-monitoring/' _output/generated-manifest/deployment.yaml
         oc apply -f _output/generated-manifest/deployment.yaml
         echo "Validating Kepler Install"
@@ -217,6 +409,8 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATION_MULTIPLIER_ENV: "9"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=no-kepler
     test:
     - chain: openshift-qe-cluster-density-v2
@@ -238,8 +432,10 @@ tests:
       ENABLE_LOCAL_INDEX: "true"
       EXTRA_FLAGS: --churn-duration=20m
       ITERATIONS_PER_NAMESPACE: "1"
+      METRIC_PROFILES: ' --metrics-profile=metrics-profiles/kepler/metrics.yaml'
       NAMESPACED_ITERATIONS: "true"
       PODS_PER_NODE: "200"
+      PROFILE_TYPE: regular
       USER_METADATA: layeredProduct=no-kepler
     test:
     - chain: openshift-qe-node-density-heavy
