node observability agent: preserve mirroring history

diff --git a/ci-operator/jobs/infra-image-mirroring.yaml b/ci-operator/jobs/infra-image-mirroring.yaml
--- a/ci-operator/jobs/infra-image-mirroring.yaml
+++ b/ci-operator/jobs/infra-image-mirroring.yaml
@@ -1263,6 +1263,16 @@ periodics:
         set -o errexit
         failures=0
         for mapping in /etc/imagemirror/mapping_node_observability_operator*; do
+          ciimage=$(cat ${mapping} | cut -d ' ' -f1)
+          quayimage=$(cat ${mapping} | cut -d ' ' -f2)
+          digest=$(oc image info ${ciimage} | grep 'Digest:' | tr -d ' ' | cut -d ':' -f2-)
+          shorttag=$(echo ${digest} | cut -d: -f2 | grep -oP '^.{12}')
+          quayimageshort=${quayimage/:*/:${shorttag}}
+          echo "Running: oc image mirror --keep-manifest-list ${ciimage}=${quayimageshort} --skip-multiple-scopes"
+          if ! oc image mirror --keep-manifest-list ${ciimage}=${quayimageshort} --skip-multiple-scopes; then
+            echo "ERROR: Failed to mirror images from $mapping to ${quayimageshort}"
+            failures=$((failures+1))
+          fi
           echo "Running: oc image mirror --keep-manifest-list -f=$mapping --skip-multiple-scopes"
           if ! oc image mirror --keep-manifest-list -f="$mapping" --skip-multiple-scopes; then
             echo "ERROR: Failed to mirror images from $mapping"
