fixes

diff --git a/ci-operator/jobs/infra-periodics.yaml b/ci-operator/jobs/infra-periodics.yaml
--- a/ci-operator/jobs/infra-periodics.yaml
+++ b/ci-operator/jobs/infra-periodics.yaml
@@ -109,6 +109,7 @@ periodics:
       - --slack-token-path=/etc/slack/oauth_token
       - --pager-duty-token-file=/etc/pagerduty/token
       - --kubeconfig-dir=/etc/build-farm-credentials
+      - --kubeconfig-suffix=config
       - --week-start=true
       command:
       - /usr/bin/sprint-automation
@@ -220,7 +221,7 @@ periodics:
       - --confirm
       command:
       - /ko-app/commenter
-      image: gcr.io/k8s-prow/commenter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/commenter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -246,6 +247,7 @@ periodics:
       - --namespace=ci
       - --dry-run=true
       - --kubeconfig-dir=/etc/build-farm-credentials
+      - --kubeconfig-suffix=config
       command:
       - /usr/bin/serviceaccount-secret-rotation-trigger
       image: serviceaccount-secret-rotation-trigger:latest
@@ -294,7 +296,7 @@ periodics:
       - --confirm
       command:
       - /ko-app/commenter
-      image: gcr.io/k8s-prow/commenter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/commenter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -340,7 +342,7 @@ periodics:
       - --confirm
       command:
       - /ko-app/commenter
-      image: gcr.io/k8s-prow/commenter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/commenter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -386,7 +388,7 @@ periodics:
       - --confirm
       command:
       - /ko-app/commenter
-      image: gcr.io/k8s-prow/commenter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/commenter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -436,7 +438,7 @@ periodics:
       - --confirm
       command:
       - /ko-app/commenter
-      image: gcr.io/k8s-prow/commenter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/commenter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -486,7 +488,7 @@ periodics:
       - --confirm
       command:
       - /ko-app/commenter
-      image: gcr.io/k8s-prow/commenter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/commenter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -535,7 +537,7 @@ periodics:
       - --confirm
       command:
       - /ko-app/commenter
-      image: gcr.io/k8s-prow/commenter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/commenter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -584,7 +586,7 @@ periodics:
       - --confirm
       command:
       - /ko-app/commenter
-      image: gcr.io/k8s-prow/commenter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/commenter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -637,7 +639,7 @@ periodics:
           secretKeyRef:
             key: appid
             name: openshift-prow-github-app
-      image: gcr.io/k8s-prow/label_sync:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/label_sync:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -940,7 +942,7 @@ periodics:
       - --config=core-services/prow/02_config/_bumper.yaml
       command:
       - /ko-app/generic-autobumper
-      image: gcr.io/k8s-prow/generic-autobumper:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/generic-autobumper:v20221016-ee0e1638a8
       imagePullPolicy: IfNotPresent
       name: autobump
       resources:
@@ -1161,7 +1163,7 @@ periodics:
       - --github-enabled-org=openshift
       command:
       - /ko-app/branchprotector
-      image: gcr.io/k8s-prow/branchprotector:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/branchprotector:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -1215,7 +1217,7 @@ periodics:
           secretKeyRef:
             key: appid
             name: openshift-prow-github-app
-      image: gcr.io/k8s-prow/branchprotector:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/branchprotector:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -1272,7 +1274,7 @@ periodics:
       - --github-allowed-burst=600
       command:
       - /ko-app/peribolos
-      image: gcr.io/k8s-prow/peribolos:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/peribolos:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -1348,9 +1350,10 @@ periodics:
     containers:
     - args:
       - --kubeconfig-dir=/etc/build-farm-credentials
+      - --kubeconfig-suffix=config
       command:
       - hack/config-bootstrapper.sh
-      image: gcr.io/k8s-prow/config-bootstrapper:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/config-bootstrapper:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -1703,7 +1706,9 @@ periodics:
       - --bw-allow-unused=dptp/cluster-bot-aws-account-for-ephemeral-osd
       - --bw-allow-unused=dptp/build_farm_osd_aws
       - --bw-allow-unused=dptp/build_farm_osd_gcp
+      - --bw-allow-unused=dptp/build_farm
       - --kubeconfig-dir=/etc/build-farm-credentials
+      - --kubeconfig-suffix=config
       command:
       - /usr/bin/ci-secret-bootstrap
       image: registry.ci.openshift.org/ci/ci-secret-bootstrap:latest
@@ -1926,7 +1931,7 @@ periodics:
       - --dry-run=false
       command:
       - /ko-app/invitations-accepter
-      image: gcr.io/k8s-prow/invitations-accepter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/invitations-accepter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -1958,7 +1963,7 @@ periodics:
       - --dry-run=false
       command:
       - /ko-app/invitations-accepter
-      image: gcr.io/k8s-prow/invitations-accepter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/invitations-accepter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -1990,7 +1995,7 @@ periodics:
       - --dry-run=false
       command:
       - /ko-app/invitations-accepter
-      image: gcr.io/k8s-prow/invitations-accepter:v20220916-01b0897fa8
+      image: gcr.io/k8s-prow/invitations-accepter:v20221016-ee0e1638a8
       imagePullPolicy: Always
       name: ""
       resources:
@@ -2024,10 +2029,15 @@ periodics:
       - --ignored-image-stream-tags
       - ^ocp\S*/\S+:machine-os-content$
       - --ignored-image-stream-tags
+      - ^ocp\S*/\S+:rhel-coreos-.+
+      - --ignored-image-stream-tags
       - '^openshift/origin-v3.11:'
       - --ignored-image-stream-tags
       - '^origin/4.([6-9]|\d\d+):'
+      - --ignored-image-stream-tags
+      - '^origin/scos-4.([6-9]|\d\d+):'
       - --kubeconfig-dir=/etc/build-farm-credentials
+      - --kubeconfig-suffix=config
       - --dry-run=false
       image: registry.ci.openshift.org/ci/promoted-image-governor:latest
       imagePullPolicy: Always
@@ -2316,6 +2326,7 @@ periodics:
         secretName: github-credentials-openshift-merge-robot
 - agent: kubernetes
   cluster: app.ci
+  cron: 30 1 * * *
   decorate: true
   decoration_config:
     gcs_configuration:
@@ -2336,7 +2347,6 @@ periodics:
     org: openshift
     repo: config
   hidden: true
-  interval: 24h
   labels:
     ci.openshift.io/role: infra-internal
   name: periodic-github-ldap-user-group-creator
@@ -2345,6 +2355,7 @@ periodics:
     - command:
       - /usr/bin/github-ldap-user-group-creator
       - --kubeconfig-dir=/tmp/build-farm-credentials
+      - --kubeconfig-suffix=config
       - --mapping-file=/etc/sync-rover-groups/mapping.yaml
       - --groups-file=/etc/sync-rover-groups/groups.yaml
       - --config-file=./core-services/sync-rover-groups/_config.yaml
@@ -2535,3 +2546,85 @@ periodics:
     - name: token
       secret:
         secretName: github-credentials-openshift-bot
+- agent: kubernetes
+  cluster: app.ci
+  cron: 0 1 * * */1
+  decorate: true
+  extra_refs:
+  - base_ref: master
+    org: openshift
+    repo: origin
+  labels:
+    ci.openshift.io/role: infra
+  name: periodic-update-origin-disruption-alert-data
+  spec:
+    containers:
+    - args:
+      - -c
+      - |
+        set -o errexit
+        set -o nounset
+        set -o pipefail
+
+        leeway_percent=30
+
+        echo "Updating alerts data"
+        /usr/bin/job-run-aggregator analyze-historical-data \
+        --current ./pkg/synthetictests/allowedalerts/query_results.json \
+        --output-file ./pkg/synthetictests/allowedalerts/query_results.json \
+        --data-type alerts \
+        --leeway $leeway_percent \
+        --google-service-account-credential-file /etc/bigquery/token
+
+        echo "Updating disruptions data"
+        /usr/bin/job-run-aggregator analyze-historical-data \
+        --current ./pkg/synthetictests/allowedbackenddisruption/query_results.json \
+        --output-file ./pkg/synthetictests/allowedbackenddisruption/query_results.json \
+        --data-type disruptions \
+        --leeway $leeway_percent \
+        --google-service-account-credential-file /etc/bigquery/token
+
+        mv pr_message.md /var/tmp/
+
+        extra_flag=""
+        if [ -f "require_review" ]; then
+            echo "review required"
+            cat require_review
+            extra_flag="-pr-assignee dgoodwin"
+            rm require_review
+        else
+            echo "review not required"
+            # off for now
+            # extra_flag="-self-approve"
+        fi
+
+        /usr/bin/prcreator \
+        -github-token-path=/etc/github/oauth \
+        -organization=openshift \
+        -repo=origin \
+        -git-message="Updated synthetic tests" \
+        -pr-message "$(cat /var/tmp/pr_message.md)" \
+        -pr-title="Automated - Update synthetic test data" \
+        $extra_flag
+      command:
+      - /bin/bash
+      image: registry.ci.openshift.org/ci/auto-aggregator-job-names:latest
+      imagePullPolicy: Always
+      name: auto-aggregator-job-names
+      resources:
+        requests:
+          cpu: 500m
+      volumeMounts:
+      - mountPath: /etc/github
+        name: token
+        readOnly: true
+      - mountPath: /etc/bigquery
+        name: bg-token
+        readOnly: true
+    volumes:
+    - name: token
+      secret:
+        secretName: github-credentials-openshift-bot
+    - name: bg-token
+      secret:
+        secretName: ci-data-bigquery-readonly
