Attempt retries in supplemental image mirroring

diff --git a/ci-operator/jobs/infra-image-mirroring.yaml b/ci-operator/jobs/infra-image-mirroring.yaml
--- a/ci-operator/jobs/infra-image-mirroring.yaml
+++ b/ci-operator/jobs/infra-image-mirroring.yaml
@@ -959,10 +959,16 @@ periodics:
         failures=0
         for mapping in /etc/imagemirror/mapping_supplemental_ci_images_*; do
           echo "Running: oc image mirror -f=$mapping --skip-multiple-scopes"
-          if ! oc image mirror -f="$mapping" --skip-multiple-scopes; then
-            echo "ERROR: Failed to mirror images from $mapping"
-            failures=$((failures+1))
-          fi
+          attempts=3
+          for attempt in $( seq $attempts ); do
+            if ! oc image mirror -f="$mapping" --skip-multiple-scopes; then
+              break
+            fi
+            if [[ $attempt -eq $attempts ]]; then
+              echo "ERROR: Failed to mirror images from $mapping after $attempts attempts"
+              failures=$((failures+1))
+            fi
+          done
         done
         exit $failures
       command:
