Add image mirroring

diff --git a/ci-operator/jobs/infra-image-mirroring.yaml b/ci-operator/jobs/infra-image-mirroring.yaml
--- a/ci-operator/jobs/infra-image-mirroring.yaml
+++ b/ci-operator/jobs/infra-image-mirroring.yaml
@@ -100,6 +100,54 @@ periodics:
   cron: '@hourly'
   decorate: true
   labels:
+    ci.openshift.io/area: openshift-azure
+    ci.openshift.io/role: image-mirroring
+  name: periodic-image-mirroring-openshift-azure
+  spec:
+    containers:
+    - args:
+      - -c
+      - |
+        set -o errexit
+        failures=0
+        for mapping in /etc/imagemirror/mapping_open_cluster_management*; do
+          echo "Running: oc image mirror -f=$mapping --skip-multiple-scopes"
+          if ! oc image mirror -f="$mapping" --skip-multiple-scopes; then
+            echo "ERROR: Failed to mirror images from $mapping"
+            failures=$((failures+1))
+          fi
+        done
+        exit $failures
+      command:
+      - /bin/bash
+      env:
+      - name: HOME
+        value: /home/mirror
+      image: quay.io/openshift/origin-cli:4.3
+      imagePullPolicy: Always
+      name: ""
+      resources:
+        requests:
+          cpu: 500m
+      volumeMounts:
+      - mountPath: /home/mirror/.docker/config.json
+        name: push
+        readOnly: true
+        subPath: config.json
+      - mountPath: /etc/imagemirror
+        name: config
+    volumes:
+    - name: push
+      secret:
+        secretName: registry-push-credentials-quay.io-openshift-azure
+    - configMap:
+        name: image-mirror-mappings
+      name: config
+- agent: kubernetes
+  cluster: api.ci
+  cron: '@hourly'
+  decorate: true
+  labels:
     ci.openshift.io/area: openshift
     ci.openshift.io/role: image-mirroring
   name: periodic-image-mirroring-openshift
