Update openshift-kni-commatrix-main.yaml

diff --git a/ci-operator/config/openshift-kni/commatrix/openshift-kni-commatrix-main.yaml b/ci-operator/config/openshift-kni/commatrix/openshift-kni-commatrix-main.yaml
--- a/ci-operator/config/openshift-kni/commatrix/openshift-kni-commatrix-main.yaml
+++ b/ci-operator/config/openshift-kni/commatrix/openshift-kni-commatrix-main.yaml
@@ -24,6 +24,22 @@ tests:
   commands: make lint
   container:
     from: src
+- as: krew test
+  commands: |
+    # Check if krew is installed, if not install it
+    if ! command -v krew &> /dev/null; then
+      echo "krew not found, installing..."
+      curl -fsSL https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz | tar xz -C /tmp
+      mv /tmp/krew-*/* /usr/local/bin/
+    fi
+    
+    oc krew install --manifest=cmd/.krew.yaml
+    oc commatrix generate
+  from: src
+  resources:
+    requests:
+      cpu: 100m
+      memory: 200Mi
 - as: commatrix-e2e-tests
   steps:
     cluster_profile: aws-telco
@@ -31,7 +47,7 @@ tests:
       BASE_DOMAIN: telco5g-ci.devcluster.openshift.com
       USER_TAGS: |
         ci-job-source prowci
-        ci-job-branch main
+        ci-job-branch krew-test
         ci-job-fullname openshift-kni-commatrix-e2e-tests-main
         ci-job-type commatrix-e2e-tests
         ci-repo-name commatrix
@@ -45,7 +61,7 @@ tests:
           cpu: 100m
           memory: 200Mi
     - ref: openshift-e2e-test
-    workflow: openshift-e2e-aws-ovn-serial
+    workflow: openshift-e2e-aws-ovn-serial 
 - as: security
   optional: true
   steps:
