updated commands

diff --git a/ci-operator/config/openshift/analytics-operator/openshift-analytics-operator-main.yaml b/ci-operator/config/openshift/analytics-operator/openshift-analytics-operator-main.yaml
--- a/ci-operator/config/openshift/analytics-operator/openshift-analytics-operator-main.yaml
+++ b/ci-operator/config/openshift/analytics-operator/openshift-analytics-operator-main.yaml
@@ -75,12 +75,30 @@ tests:
     test:
     - as: test
       cli: latest
-      commands: "echo \"command execution started\"\noc version\n# Make kubectl available
-        by creating a symlink to oc.\npushd \"$CLI_DIR\"\nif [ ! -f kubectl ]; then\n
-        \   ln -s oc kubectl\nfi\npopd\nset +e \nGOFLAGS=\"\" sh ./tests/run-e2e.sh
-        --no-build --image-base registry.ci.openshift.org/osa --version latest\nif
-        [ $? -eq 0 ] \nthen \n  echo \"Successfully executed E2E test script\" \nelse
-        \n  echo \"E2E test failed\"  \n  exit 1\nfi\n"
+      commands: |
+        echo "command execution started"
+        oc version
+        # Make kubectl available by creating a symlink to oc.
+        pushd "$CLI_DIR"
+        if [ ! -f kubectl ]; then
+            ln -s oc kubectl
+        fi
+        popd
+        set +e 
+        echo "creating temp project"
+        oc new-project temp-osa
+        oc project temp-osa 
+        echo "Running shell script"
+        GOFLAGS="" sh ./tests/run-e2e.sh --no-build --image-base registry.ci.openshift.org/osa --version latest
+        echo "delete temp project"
+        oc delete project temp-osa 
+        if [ $? -eq 0 ] 
+        then 
+          echo "Successfully executed E2E test script" 
+        else 
+          echo "E2E test failed"  
+          exit 1
+        fi
       from: src
       resources:
         requests:
