update logic to clean stale deploys

diff --git a/ci-operator/step-registry/hypershift/ibmcloud/cluster-claim/hypershift-ibmcloud-cluster-claim-chain.yaml b/ci-operator/step-registry/hypershift/ibmcloud/cluster-claim/hypershift-ibmcloud-cluster-claim-chain.yaml
--- a/ci-operator/step-registry/hypershift/ibmcloud/cluster-claim/hypershift-ibmcloud-cluster-claim-chain.yaml
+++ b/ci-operator/step-registry/hypershift/ibmcloud/cluster-claim/hypershift-ibmcloud-cluster-claim-chain.yaml
@@ -3,40 +3,27 @@ chain:
   steps:
   - as: cluster-claim-check
     commands: |-
-      # Retrieve the creation timestamp of the deployment if it exists
-      if CREATION_TIMESTAMP=$(oc --kubeconfig="${MANAGEMENT_CLUSTER_KUBECONFIG}" get deploy -n hypershift operator -o jsonpath='{.metadata.creationTimestamp}' 2>/dev/null); then
-        # Get current timestamp and convert it
-        CURRENT_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
-        CREATION_TIME=$(date -d"${CREATION_TIMESTAMP}" +"%s")
-        CURRENT_TIME=$(date -d"${CURRENT_TIMESTAMP}" +"%s")
-
-        # Calculate the age of the deployment in seconds
-        AGE=$((CURRENT_TIME - CREATION_TIME))
-
-        # Get the build ID of the deployment
-        BUILD_ID=$(oc --kubeconfig="${MANAGEMENT_CLUSTER_KUBECONFIG}" get deploy -n hypershift operator -o jsonpath='{.metadata.labels.build-id}' || true)
-
-        # Print information about the deployment
-        echo "HyperShift operator deployment found on the PR test cluster. There may be another PR test in progress."
-        if [[ "${BUILD_ID}" != "" ]]; then
-          echo "Build ${BUILD_ID} installed the current HO deployment."
-        fi
-
-        # Check if the deployment age is over a day (86400 seconds)
-        if [[ $AGE -gt 86400 ]]; then
-          # If the deployment is over a day old, attempt to delete it
-          if oc --kubeconfig="${MANAGEMENT_CLUSTER_KUBECONFIG}" delete deploy -n hypershift operator; then
-            echo "Deployment deleted successfully."
-          else
-            echo "Failed to delete deployment."
-          fi
-        else
-          echo "Skipping deletion because deployment is still recent"
-        fi
-      else
-        echo "HyperShift operator deployment not found. Skipping deletion."
+      export KUBECONFIG="${MANAGEMENT_CLUSTER_KUBECONFIG}"
+      STATUS=$(oc get deploy -n hypershift operator -o jsonpath='{.status.conditions[?(@.type=="Available")].status}' 2>/dev/null)
+      BUILD_ID=$(oc get deploy -n hypershift operator -o jsonpath='{.metadata.labels.build-id}')
+      AGE=$(oc get deploy -n hypershift operator -o jsonpath='{.metadata.creationTimestamp}')
+      CREATION_TIME=$(date -d"${AGE}" +"%s")
+      CURRENT_TIME=$(date -u +"%s")
+      AGE_IN_SECONDS=$((CURRENT_TIME - CREATION_TIME))
+      
+      if [[ -n "${BUILD_ID}" ]]; then
+          echo "HyperShift operator deployment found on the PR test cluster. There may be another PR test in progress." && echo "Build ${BUILD_ID} installed the current HO deployment."
       fi
-      exit 1
+
+      # Check if deployment exists and its unhealthy then delete
+      if [[ "$STATUS" != "True" ]] || [[ $AGE_IN_SECONDS -gt 86400 ]]; then
+          echo "HyperShift operator deployment is stale. Deleting."
+          oc delete deploy -n hypershift operator
+      else
+          echo "ERROR: Failing."
+          exit 1
+      fi
+
     credentials:
     - mount_path: /etc/ibmcloud/secrets
       name: hypershift-ibm-managed-ci-creds
