reorder create logic for proper teardown

diff --git a/ci-operator/templates/cluster-launch-e2e-azure.yaml b/ci-operator/templates/cluster-launch-e2e-azure.yaml
--- a/ci-operator/templates/cluster-launch-e2e-azure.yaml
+++ b/ci-operator/templates/cluster-launch-e2e-azure.yaml
@@ -87,8 +87,6 @@ objects:
         trap 'touch /tmp/shared/exit' EXIT
         trap 'kill $(jobs -p); exit 0' TERM
 
-        cp "$(which oc)" /tmp/shared/
-
         mkdir -p "${HOME}"
 
         # wait until the setup job creates admin.kubeconfig
@@ -113,9 +111,7 @@ objects:
         PATH=/usr/libexec/origin:$PATH
 
         # create the environment, but exit before we run tests
-        # TODO: RUN TESTS HERE
         oc get pods --all-namespaces 
-        exit 0
 
     # Runs an install
     - name: setup
@@ -139,13 +135,17 @@ objects:
       - -c
       - |
        #!/bin/bash
-        # error handling and sync code
         set -euo pipefail
-
+        
+        # trap acts as a switch/router for the next phases
         trap 'rc=$?; if [[ $rc -ne 0 ]]; then 
-        # on failure we copy details for clean-up
-        cp -r /go/src/github.com/openshift/openshift-azure/_data /tmp/shared/ &>/dev/null
-        touch /tmp/shared/exit; fi; exit $rc' EXIT
+          # on failure copy details for teardown
+          cp -r /go/src/github.com/openshift/openshift-azure/_data /tmp/shared/ &>/dev/null
+          touch /tmp/shared/exit;
+        else
+          # on succes copy details for tests
+          cp -r /go/src/github.com/openshift/openshift-azure/_data /tmp/shared/
+        fi; exit $rc' EXIT
         trap 'kill $(jobs -p); exit 0' TERM
 
         # Cluster creation specific configuration.
@@ -155,7 +155,6 @@ objects:
         # aad integration configuration - we dont test aad so populate as dummy
         export AZURE_AAD_CLIENT_ID=$AZURE_CLIENT_ID
         export AZURE_AAD_CLIENT_SECRET=$AZURE_CLIENT_SECRET
-        # TODO: Configure these from prow
         echo "Using sync image ${SYNC_IMAGE}"
         export DNS_DOMAIN=osadev.cloud
         export DNS_RESOURCEGROUP=dns
@@ -163,13 +162,9 @@ objects:
         export RUN_SYNC_LOCAL=true
         export IMAGE_RESOURCEGROUP=images
         export IMAGE_RESOURCENAME=$(az image list -g $IMAGE_RESOURCEGROUP -o json --query "[?starts_with(name, '${DEPLOY_OS:-rhel7}-${DEPLOY_VERSION//v}') && tags.valid=='true'].name | sort(@) | [-1]" | tr -d '"')
-        # TODO: for full e2e image needs to be built too  
+        # create cluster for test
         cd /go/src/github.com/openshift/openshift-azure/
-       
         ./hack/create.sh ${INSTANCE_PREFIX}
-
-        # if completed pass generated data to other stage
-        cp -r /go/src/github.com/openshift/openshift-azure/_data /tmp/shared/
 
     # Performs cleanup of all created resources
     - name: teardown
@@ -193,6 +188,8 @@ objects:
       - -c
       - |
         #!/bin/bash
+
+        # teardown is collecting debug data and deleting all used resources
         function teardown() {
           set +e
           mkdir -p "${HOME}"
@@ -217,6 +214,7 @@ objects:
         trap 'teardown' EXIT
         trap 'kill $(jobs -p); exit 0' TERM
 
+        # teardown is triggered on file marker
         for i in `seq 1 120`; do
           if [[ -f /tmp/shared/exit ]]; then
             exit 0
