Try 1 deploy
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>

diff --git a/ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v7.yaml b/ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v7.yaml
--- a/ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v7.yaml
+++ b/ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v7.yaml
@@ -36,6 +36,20 @@ tests:
       commands: |
         echo ${TEST_SKIPS}
         oc get proxy/cluster -o yaml
+        chectl server:deploy --installer=operator
+        catchFinish() {
+          result=$?
+          chectl server:logs --chenamespace=eclipse-che --directory=/tmp/artifacts/che
+          if [ "$result" != "0" ]; then
+            echo "[ERROR] Job failed."
+            mkdir -p ${ARTIFACTS_DIR}
+          else
+            echo "[INFO] Job completed successfully."
+          fi
+
+          echo "[INFO] Please check github actions artifacts."
+          exit $result
+        }
       env:
       - name: TEST_SKIPS
       from: src
