Add krkn-ai command to osde2e hypershift-pr-check (#73913)
also:
- remove run_if_changed to avoid auto triggering on each commit,
- but return success if no orchestrator files changed

diff --git a/ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml b/ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
--- a/ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
+++ b/ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
@@ -28,20 +28,41 @@ tests:
 - always_run: false
   as: hypershift-pr-check
   commands: |
+    # Check if there are changes in pkg/ or cmd/ directories
+    if ! git diff --name-only origin/main...HEAD | grep -qE '^(pkg/|cmd/)'; then
+      echo "No changes detected in pkg/ or cmd/ directories. Skipping test."
+      exit 0
+    fi
+
     export GOFLAGS=""
     export REPORT_DIR="$ARTIFACT_DIR"
     export CONFIGS="hypershift"
     export CHANNEL="stable"
+    export SHARED_DIR="tmp/"
     export SKIP_MUST_GATHER="true"
+    export SKIP_DESTROY_CLUSTER="true"
     export SECRET_LOCATIONS="/usr/local/osde2e-common,/usr/local/osde2e-credentials,/usr/local/osde2e-hypershift-credentials"
 
     go mod tidy
     make build
-
+    echo "Provisioning and running e2e commands"
     out/osde2e test --secret-locations ${SECRET_LOCATIONS} --configs ${CONFIGS}
+
+    echo "Copying cluster ID for krknai commands."
+    if [[ ! -f "${SHARED_DIR}/cluster-id" ]];
+    then
+        echo "'cluster-id' not found in shared dir. Cluster may not have been provisioned."
+        exit 1
+    fi
+    echo "Running krknai commands"
+    export DRY_RUN="TRUE"
+    out/osde2e krkn-ai --configs "${CONFIGS}" --secret-locations "${SECRET_LOCATIONS}" --cluster-id "$(cat "${SHARED_DIR}/cluster-id")"
+    echo "Cleaning up"
+    export SKIP_DESTROY_CLUSTER="false"
+    out/osde2e cleanup --configs "${CONFIGS}" --secret-locations "${SECRET_LOCATIONS}" --cluster-id "$(cat "${SHARED_DIR}/cluster-id")"
+    echo "Finished osde2e pr checks on ROSA hypershift."
   container:
     from: src
-  run_if_changed: ^(pkg\/common\/|pkg\/e2e\/)$
   secrets:
   - mount_path: /usr/local/osde2e-common
     name: osde2e-common
