temp change to debug
Signed-off-by: sahare <sahare@redhat.com>

diff --git a/ci-operator/config/stolostron/mtv-integrations/stolostron-mtv-integrations-main.yaml b/ci-operator/config/stolostron/mtv-integrations/stolostron-mtv-integrations-main.yaml
--- a/ci-operator/config/stolostron/mtv-integrations/stolostron-mtv-integrations-main.yaml
+++ b/ci-operator/config/stolostron/mtv-integrations/stolostron-mtv-integrations-main.yaml
@@ -31,18 +31,18 @@ tests:
 - as: sonar
   commands: |
     set -euo pipefail
-
     export HOME="/tmp"
     export SELF="make -f /opt/build-harness/Makefile.prow"
-
     SONAR_GO_TEST_ARGS="$(go list ./... | grep -v /e2e || true)"
     export SONAR_GO_TEST_ARGS
-
+    echo "SONAR_GO_TEST_ARGS=$SONAR_GO_TEST_ARGS"
+    ls -l /opt/build-harness/Makefile.prow || true
+    echo "Dumping failing makefile..."
+    cat -n /opt/build-harness-extensions/modules/sonar/Makefile | tail -n +20 | head -n 20
     if [ -z "$SONAR_GO_TEST_ARGS" ]; then
       echo "No test packages to analyze. Exiting gracefully."
       exit 0
     fi
-
     make -f /opt/build-harness/Makefile.prow sonar/go/prow
   container:
     from: src
